package com.anibalxyz.users.application;

/**
 * An interface that defines a contract for accessing environment-specific configuration values.
 *
 * <p>This abstraction decouples the application layer from the concrete source of configuration
 * (e.g., system properties, .env files). It allows services like {@link UserService} to depend on
 * configuration without knowing how it's loaded.
 *
 * @author Generated by AI
 */
public interface EnvironmentSource {
  /**
   * @return The current application environment (e.g., "development", "test").
   */
  String APP_ENV();

  /**
   * @return The computational cost (log rounds) for the BCrypt password hashing algorithm.
   */
  int BCRYPT_LOG_ROUNDS();
}
