package com.anibalxyz.users.application;

import com.anibalxyz.server.config.EnvVarSet;
import com.anibalxyz.users.application.exception.EntityNotFoundException;
import com.anibalxyz.users.application.in.UserUpdatePayload;
import com.anibalxyz.users.domain.Email;
import com.anibalxyz.users.domain.PasswordHash;
import com.anibalxyz.users.domain.User;
import com.anibalxyz.users.domain.UserRepository;
import java.util.List;

/**
 * Application service for user-related use cases.
 *
 * <p>This class orchestrates the domain layer to perform operations such as creating, retrieving,
 * updating, and deleting users. It contains the application-specific business logic and acts as a
 * boundary between the presentation layer (API) and the domain layer.
 *
 * @author Generated by AI
 */
public class UserService {
  private final UserRepository userRepository;
  private final EnvVarSet env;

  // TODO: make 'env' an interface
  /**
   * Constructs a UserService with its required dependencies.
   *
   * @param userRepository The repository for user data persistence.
   * @param env The application's environment variables provider.
   * @author Generated by AI
   */
  public UserService(UserRepository userRepository, EnvVarSet env) {
    this.userRepository = userRepository;
    this.env = env;
  }

  /**
   * Retrieves all users.
   *
   * @return A list of all {@link User} objects.
   * @author Generated by AI
   */
  public List<User> getAllUsers() {
    return userRepository.findAll();
  }

  /**
   * Retrieves a single user by their ID.
   *
   * @param id The ID of the user to retrieve.
   * @return The found {@link User} object.
   * @throws EntityNotFoundException if no user with the given ID is found.
   * @author Generated by AI
   */
  public User getUserById(int id) throws EntityNotFoundException {
    return userRepository
        .findById(id)
        .orElseThrow(() -> new EntityNotFoundException("User with id " + id + " not found"));
  }

  /**
   * Creates a new user based on the provided payload.
   *
   * @param payload The data for the new user, implementing {@link UserUpdatePayload}.
   * @return The newly created and persisted {@link User} object.
   * @throws IllegalArgumentException if the email is already in use.
   * @author Generated by AI
   */
  public User createUser(UserUpdatePayload payload) throws IllegalArgumentException {
    Email email = new Email(payload.email());
    userRepository
        .findByEmail(email)
        .ifPresent(
            user -> {
              throw new IllegalArgumentException("Email already in use. Please use another");
            });
    PasswordHash passwordHash = PasswordHash.generate(payload.password(), env.BCRYPT_LOG_ROUNDS());
    return userRepository.save(new User(payload.name(), email, passwordHash));
  }

  /**
   * Updates an existing user's information.
   *
   * <p>Fields in the payload are applied conditionally. A null field in the payload means that
   * property will not be updated.
   *
   * @param id The ID of the user to update.
   * @param payload A {@link UserUpdatePayload} containing the fields to update.
   * @return The updated {@link User} object.
   * @throws EntityNotFoundException if no user with the given ID is found.
   * @throws IllegalArgumentException if the new email is already in use by another user.
   * @author Generated by AI
   */
  public User updateUserById(Integer id, UserUpdatePayload payload)
      throws IllegalArgumentException, EntityNotFoundException {
    User user =
        userRepository
            .findById(id)
            .orElseThrow(() -> new EntityNotFoundException("User with id " + id + " not found"));
    if (payload.name() != null) {
      user = user.withName(payload.name());
    }
    if (payload.email() != null) {
      Email newEmail = new Email(payload.email());

      // Avoids an unneeded DB query (findByEmail)
      if (!newEmail.equals(user.getEmail())) {
        userRepository
            .findByEmail(newEmail)
            .ifPresent(
                existingUser -> {
                  throw new IllegalArgumentException("Email already in use. Please use another");
                });
        user = user.withEmail(newEmail);
      }
    }

    if (payload.password() != null) {
      user =
          user.withPasswordHash(PasswordHash.generate(payload.password(), env.BCRYPT_LOG_ROUNDS()));
    }
    return userRepository.save(user);
  }

  /**
   * Deletes a user by their ID.
   *
   * @param id The ID of the user to delete.
   * @throws EntityNotFoundException if the user could not be found or was not deleted.
   * @author Generated by AI
   */
  public void deleteUserById(int id) throws EntityNotFoundException {
    boolean wasDeleted = userRepository.deleteById(id);
    if (!wasDeleted) {
      throw new EntityNotFoundException("User with id " + id + " not found");
    }
  }
}
