package com.anibalxyz.features.users.application;

import com.anibalxyz.features.common.Result;
import com.anibalxyz.features.common.application.ValidationNotification;
import com.anibalxyz.features.common.application.exception.*;
import com.anibalxyz.features.common.domain.error.DomainError;
import com.anibalxyz.features.users.application.env.UsersEnvironment;
import com.anibalxyz.features.users.application.in.CreateUserCommand;
import com.anibalxyz.features.users.application.in.UpdateUserCommand;
import com.anibalxyz.features.users.domain.*;
import com.anibalxyz.features.users.domain.error.*;
import java.util.List;
import java.util.Optional;

/**
 * Application service for user-related use cases.
 *
 * <p>This class orchestrates the domain layer to perform operations such as creating, retrieving,
 * updating, and deleting users. It contains the application-specific business logic and acts as a
 * boundary between the presentation layer (API) and the domain layer.
 *
 * @author Generated by AI
 */
public class UserService {
  private final UsersEnvironment env;
  private final UserRepository userRepository;

  /**
   * Constructs a UserService with its required dependencies.
   *
   * @param env An interface for providing environment-specific configuration.
   * @param userRepository The repository for user data persistence.
   */
  public UserService(UsersEnvironment env, UserRepository userRepository) {
    this.env = env;
    this.userRepository = userRepository;
  }

  /**
   * Retrieves all users.
   *
   * @return A list of all {@link User} objects.
   */
  public List<User> getAllUsers() {
    return userRepository.findAll();
  }

  /**
   * Retrieves a single user by their ID.
   *
   * @param id The ID of the user to retrieve.
   * @return The found {@link User} object.
   */
  public Result<User, UserNotFoundError> getUserById(int id) {
    return userRepository
        .findById(id)
        .<Result<User, UserNotFoundError>>map(Result::success)
        .orElseGet(() -> Result.failure(UserNotFoundError.byId(id)));
  }

  // TODO: make it a sealed interface
  //       I found it difficult to use, e.g. during tests. Consumer is not able to know the
  //       available errors just by reading the method signature -> it must read the method
  public Result<User, DomainError> getUserByEmail(String email) {
    Result<Email, InvalidEmailError> result = Email.of(email);
    if (result.isFailure()) {
      return Result.failure(result.getError());
    }

    return userRepository
        .findByEmail(result.getValue())
        .map(Result::<User, DomainError>success)
        .orElseGet(() -> Result.failure(UserNotFoundError.byEmail(email)));
  }

  public Result<User, ValidationNotification<UserDomainError>> createUser(
      CreateUserCommand command) {
    ValidationNotification<UserDomainError> notification = new ValidationNotification<>();

    Result<Name, InvalidNameError> nameResult = Name.of(command.name());
    if (nameResult.isFailure()) {
      notification.add("name", nameResult.getError());
    }

    Result<Email, InvalidEmailError> emailResult = Email.of(command.email());
    if (emailResult.isFailure()) {
      notification.add("email", emailResult.getError());
    } else {
      userRepository
          .findByEmail(emailResult.getValue())
          .ifPresent(user -> notification.add("email", new EmailAlreadyTakenError()));
    }

    Result<PasswordHash, InvalidPasswordError> passwordResult =
        PasswordHash.generate(command.password(), env.BCRYPT_LOG_ROUNDS());
    if (passwordResult.isFailure()) {
      notification.add("password", passwordResult.getError());
    }

    if (notification.hasErrors()) {
      return Result.failure(notification);
    }

    return Result.success(
        userRepository.save(
            new User(nameResult.getValue(), emailResult.getValue(), passwordResult.getValue())));
  }

  public sealed interface UpdateUserByIdError {
    record NotFound(UserNotFoundError error) implements UpdateUserByIdError {}

    record EmptyCommand() implements UpdateUserByIdError {}

    record ValidationFailed(ValidationNotification<UserDomainError> notification)
        implements UpdateUserByIdError {}
  }

  public Result<User, UpdateUserByIdError> updateUserById(Integer id, UpdateUserCommand command) {
    // Fail-fast: avoids unnecessary expensive operations (e.g. bcrypt) when all fields are absent.
    // Redundant with VO null checks, but the performance trade-off justifies it.
    if (!command.hasAtLeastOneField()) {
      return Result.failure(new UpdateUserByIdError.EmptyCommand());
    }

    // TODO: I/O operation should be the last one
    Optional<User> userOptional = userRepository.findById(id);
    if (userOptional.isEmpty()) {
      return Result.failure(new UpdateUserByIdError.NotFound(UserNotFoundError.byId(id)));
    }
    User user = userOptional.get();

    ValidationNotification<UserDomainError> notification = new ValidationNotification<>();

    Result<Name, InvalidNameError> nameResult = Name.of(command.name());
    if (nameResult.isSuccess()) {
      user = user.withName(nameResult.getValue());
    } else if (!(nameResult.getError().getReason() instanceof InvalidNameError.Reason.Absent)) {
      notification.add("name", nameResult.getError());
    }

    Result<Email, InvalidEmailError> emailResult = Email.of(command.email());
    if (emailResult.isSuccess()) {
      Email newEmail = emailResult.getValue();
      if (!newEmail.equals(user.email())) {
        if (userRepository.findByEmail(newEmail).isPresent()) {
          notification.add("email", new EmailAlreadyTakenError());
        } else {
          user = user.withEmail(newEmail);
        }
      }
    } else if (!(emailResult.getError().getReason() instanceof InvalidEmailError.Reason.Absent)) {
      notification.add("email", emailResult.getError());
    }

    Result<PasswordHash, InvalidPasswordError> passResult =
        PasswordHash.generate(command.password(), env.BCRYPT_LOG_ROUNDS());

    if (passResult.isSuccess()) {
      user = user.withPasswordHash(passResult.getValue());
    } else if (!(passResult.getError().getReason() instanceof InvalidPasswordError.Reason.Absent)) {
      notification.add("password", passResult.getError());
    }

    if (notification.hasErrors()) {
      return Result.failure(new UpdateUserByIdError.ValidationFailed(notification));
    }

    return Result.success(userRepository.save(user));
  }

  /**
   * Deletes a user by their ID.
   *
   * @param id The ID of the user to delete.
   */
  public Result<Void, UserNotFoundError> deleteUserById(int id) {
    return userRepository.deleteById(id)
        ? Result.success(null)
        : Result.failure(UserNotFoundError.byId(id));
  }
}
