package com.anibalxyz.features.users.application;

/**
 * Defines a port for providing environment configuration to the Users feature.
 *
 * <p>This interface acts as a contract that the application layer requires for
 * environment-dependent settings. It decouples the {@link UserService} from the concrete source of
 * configuration, allowing for different implementations (e.g., for production or testing).
 *
 * @author Generated by AI
 */
public interface UsersEnvironment {
  /**
   * @return The computational cost (log rounds) for the BCrypt password hashing algorithm.
   */
  int BCRYPT_LOG_ROUNDS();
}
