package com.anibalxyz.features.users.application;

import com.anibalxyz.features.common.Result;
import com.anibalxyz.features.common.application.ValidationNotification;
import com.anibalxyz.features.common.application.exception.*;
import com.anibalxyz.features.common.domain.error.DomainError;
import com.anibalxyz.features.users.application.env.UsersEnvironment;
import com.anibalxyz.features.users.application.in.CreateUserCommand;
import com.anibalxyz.features.users.application.in.UpdateUserCommand;
import com.anibalxyz.features.users.domain.Email;
import com.anibalxyz.features.users.domain.PasswordHash;
import com.anibalxyz.features.users.domain.User;
import com.anibalxyz.features.users.domain.UserRepository;
import com.anibalxyz.features.users.domain.error.InvalidEmailError;
import com.anibalxyz.features.users.domain.error.InvalidPasswordError;
import com.anibalxyz.features.users.domain.error.UserNotFoundError;
import java.util.List;
import java.util.Optional;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Application service for user-related use cases.
 *
 * <p>This class orchestrates the domain layer to perform operations such as creating, retrieving,
 * updating, and deleting users. It contains the application-specific business logic and acts as a
 * boundary between the presentation layer (API) and the domain layer.
 *
 * @author Generated by AI
 */
public class UserService {
  private static final Logger log = LoggerFactory.getLogger(UserService.class);
  private final UsersEnvironment env;
  private final UserRepository userRepository;

  /**
   * Constructs a UserService with its required dependencies.
   *
   * @param env An interface for providing environment-specific configuration.
   * @param userRepository The repository for user data persistence.
   */
  public UserService(UsersEnvironment env, UserRepository userRepository) {
    this.env = env;
    this.userRepository = userRepository;
  }

  /**
   * Retrieves all users.
   *
   * @return A list of all {@link User} objects.
   */
  public List<User> getAllUsers() {
    return userRepository.findAll();
  }

  /**
   * Retrieves a single user by their ID.
   *
   * @param id The ID of the user to retrieve.
   * @return The found {@link User} object.
   */
  public Result<User, UserNotFoundError> getUserById(int id) {
    return userRepository
        .findById(id)
        .<Result<User, UserNotFoundError>>map(Result::success)
        .orElseGet(() -> Result.failure(UserNotFoundError.byId(id)));
  }

  public Result<User, DomainError> getUserByEmail(String email) {
    Result<Email, InvalidEmailError> result = Email.of(email);
    if (result.isFailure()) {
      return Result.failure(result.getError());
    }

    return userRepository
        .findByEmail(result.getValue())
        .map(Result::<User, DomainError>success)
        .orElseGet(() -> Result.failure(UserNotFoundError.byEmail(email)));
  }

  public Result<User, ValidationNotification> createUser(CreateUserCommand command) {
    ValidationNotification notification = new ValidationNotification();
    command.validate(notification);

    Optional<Email> email = Optional.empty();
    Optional<PasswordHash> passwordHash = Optional.empty();
    if (!notification.hasErrorFor("email")) {
      Result<Email, InvalidEmailError> emailResult = Email.of(command.email());
      if (emailResult.isFailure()) {
        notification.add("email", emailResult.getError());
      } else {
        email = Optional.of(emailResult.getValue());
        userRepository
            .findByEmail(email.get())
            .ifPresent(user -> notification.addConflict("email"));
      }
    }
    if (!notification.hasErrorFor("password")) {
      Result<PasswordHash, InvalidPasswordError> passwordResult =
          PasswordHash.generate(command.password(), env.BCRYPT_LOG_ROUNDS());
      if (passwordResult.isFailure()) {
        notification.add("password", passwordResult.getError());
      } else {
        passwordHash = Optional.of(passwordResult.getValue());
      }
    }

    if (notification.hasErrors()) {
      return Result.failure(notification);
    }

    return Result.success(
        userRepository.save(
            new User(command.name(), email.orElseThrow(), passwordHash.orElseThrow())));
  }

  public sealed interface UpdateUserByIdError {
    record NotFound(UserNotFoundError error) implements UpdateUserByIdError {}

    record EmptyCommand() implements UpdateUserByIdError {}

    record ValidationFailed(ValidationNotification notification) implements UpdateUserByIdError {}
  }

  public Result<User, UpdateUserByIdError> updateUserById(Integer id, UpdateUserCommand command) {
    if (!command.hasAtLeastOneField()) {
      return Result.failure(new UpdateUserByIdError.EmptyCommand());
    }

    Optional<User> userOptional = userRepository.findById(id);
    if (userOptional.isEmpty()) {
      return Result.failure(new UpdateUserByIdError.NotFound(UserNotFoundError.byId(id)));
    }
    User user = userOptional.get();

    ValidationNotification notification = new ValidationNotification();

    switch (command.nameState()) {
      case VALID -> user = user.withName(command.name());
      case BLANK -> notification.addBlank("name");
      case NOT_PRESENT -> {}
    }

    switch (command.emailState()) {
      case VALID -> {
        Result<Email, InvalidEmailError> emailResult = Email.of(command.email());
        if (emailResult.isFailure()) {
          notification.add("email", emailResult.getError());
        } else {
          Email newEmail = emailResult.getValue();
          if (!newEmail.equals(user.getEmail())) {
            if (userRepository.findByEmail(newEmail).isPresent()) {
              notification.addConflict("email");
            } else {
              user = user.withEmail(newEmail);
            }
          }
        }
      }
      case BLANK -> notification.addBlank("email");
      case NOT_PRESENT -> {}
    }

    switch (command.passwordState()) {
      case VALID -> {
        Result<PasswordHash, InvalidPasswordError> passResult =
            PasswordHash.generate(command.password(), env.BCRYPT_LOG_ROUNDS());
        if (passResult.isFailure()) {
          notification.add("password", passResult.getError());
        } else {
          user = user.withPasswordHash(passResult.getValue());
        }
      }
      case BLANK -> notification.addBlank("password");
      case NOT_PRESENT -> {}
    }

    if (notification.hasErrors())
      return Result.failure(new UpdateUserByIdError.ValidationFailed(notification));

    return Result.success(userRepository.save(user));
  }

  /**
   * Deletes a user by their ID.
   *
   * @param id The ID of the user to delete.
   * @throws ResourceNotFoundException if the user could not be found or was not deleted.
   */
  public Result<Void, UserNotFoundError> deleteUserById(int id) {
    boolean wasDeleted = userRepository.deleteById(id);
    return wasDeleted ? Result.success(null) : Result.failure(UserNotFoundError.byId(id));
  }
}
