package com.anibalxyz.server.security;

import io.javalin.security.RouteRole;

/**
 * Defines the roles used by the AccessManager to control endpoint access.
 *
 * @author Generated by AI
 */
public enum Role implements RouteRole {
  /** A role for any user, including unauthenticated ones. */
  GUEST,
  /** A role for users who have a valid JWT. */
  AUTHENTICATED
}
