package com.anibalxyz.features.auth.application.in;

/**
 * Defines the contract for incoming data payloads for user login.
 *
 * <p>This interface is used by the {@link com.anibalxyz.features.auth.application.AuthService} to
 * decouple it from the specific DTOs of the API layer. Any request object (like LoginRequest)
 * that provides login data must implement this interface.
 *
 * @author Generated by AI
 */
public interface LoginPayload {
  /**
   * @return The user's email address.
   */
  String email();

  /**
   * @return The user's raw (plain-text) password.
   */
  String password();
}
