package com.anibalxyz.features.auth.application.env;

import com.anibalxyz.features.auth.application.JwtService;
import javax.crypto.SecretKey;

/**
 * Defines the contract for providing JWT-related environment configuration.
 *
 * <p>This interface acts as a port for environment-dependent settings required by the {@link
 * JwtService}, such as the secret, issuer, and expiration time for access tokens. It decouples the
 * service from the concrete source of configuration.
 *
 * @author Generated by AI
 */
public interface JwtEnvironment {
  /**
   * Returns the secret key used for signing and verifying JWT access tokens.
   *
   * @return The JWT secret key.
   */
  String JWT_SECRET();

  /**
   * Returns the {@link SecretKey} object used for signing and verifying JWT access tokens. This is
   * derived from the {@link #JWT_SECRET()}.
   *
   * @return The JWT secret key object.
   */
  SecretKey JWT_KEY();

  /**
   * Returns the issuer name to be included in the JWT access tokens.
   *
   * @return The JWT issuer name.
   */
  String JWT_ISSUER();

  /**
   * Returns the expiration time for JWT access tokens.
   *
   * @return The access token expiration time.
   */
  long JWT_ACCESS_EXPIRATION_TIME_MINUTES();
}
