package com.anibalxyz.features.auth.application.env;

import com.anibalxyz.features.auth.application.RefreshTokenService;
import java.time.Duration;

/**
 * Defines the contract for providing Refresh Token related environment configuration.
 *
 * <p>This interface acts as a port for environment-dependent settings required by the {@link
 * RefreshTokenService}, such as the expiration time for refresh tokens. It decouples the service
 * from the concrete source of configuration.
 *
 * @author Generated by AI
 */
public interface RefreshTokenEnvironment {
  /**
   * Returns the expiration time for refresh tokens.
   *
   * @return The refresh token expiration time.
   */
  Duration JWT_REFRESH_EXPIRATION_TIME_DAYS();

  boolean AUTH_ENABLE_TIME_WINDOW();
}
