package com.anibalxyz.users.application.exception;

/**
 * Exception thrown when a requested entity (e.g., a User) cannot be found in the data store.
 *
 * <p>This is a runtime exception because it typically represents a client error (requesting a
 * non-existent resource) or a data consistency issue that should be handled globally by the
 * application's exception handling layer, often resulting in a 404 Not Found response.
 *
 * @author Generated by AI
 */
public class EntityNotFoundException extends RuntimeException {
  /**
   * Constructs a new EntityNotFoundException with the specified detail message.
   *
   * @param message the detail message.
   */
  public EntityNotFoundException(String message) {
    super(message);
  }

  /**
   * Constructs a new EntityNotFoundException with no detail message.
   */
  public EntityNotFoundException() {
    super();
  }
}
