package com.anibalxyz.server.config.modules.definitions;

import io.javalin.config.JavalinConfig;

/**
 * Abstract base class for startup configuration modules.
 *
 * <p>Startup configuration modules are applied to the {@link JavalinConfig} object during the
 * server initialization phase, before the Javalin server instance is actually started. These
 * configurations typically involve global settings, plugin registrations, and other setup tasks.
 *
 * @author Generated by AI
 */
public abstract class StartupConfig {

  protected JavalinConfig javalinConfig;

  /**
   * Constructs a StartupConfig module.
   *
   * @param javalinConfig The JavalinConfig instance to which the configuration will be applied.
   */
  public StartupConfig(JavalinConfig javalinConfig) {
    this.javalinConfig = javalinConfig;
  }

  /**
   * Applies the startup configuration logic to the Javalin configuration.
   */
  public abstract void apply();
}
