FROM maven:3.9.9-eclipse-temurin-21

WORKDIR /app

COPY pom.xml .

# Pre-download all required dependencies and plugins for offline builds
# Does not compile the code; prepares for `mvn package` without internet
# -B: batch mode (non-interactive)
RUN mvn dependency:go-offline -B

COPY src/ ./src

# TODO: there is an scenario when the api starts at the same time that db is up but migrations did not executed yet.
#       This 3-seconds sleep **temporary** solves that. NOTE: used in dev, prod & test dockerfiles.
ENTRYPOINT ["sh", "-c", "echo 'Waiting for DB to be ready...' && sleep 3 && exec mvn compile exec:java -Dexec.mainClass=com.anibalxyz.Main"]
