FROM maven:3.9.9-eclipse-temurin-21

WORKDIR /app

COPY pom.xml .

# Pre-download all required dependencies and plugins for offline builds
# Does not compile the code; prepares for `mvn package` without internet
# -B: batch mode (non-interactive)
RUN mvn dependency:go-offline -B

COPY src/ ./src

EXPOSE 4000

ENTRYPOINT ["mvn", "compile", "exec:java", "-Dexec.mainClass=com.anibalxyz.Main"]
