package com.anibalxyz.server.config.modules.startup;

import com.fasterxml.jackson.databind.SerializationFeature;
import io.javalin.config.JavalinConfig;
import io.javalin.json.JavalinJackson;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * A {@link ServerConfig} module for applying initial, one-time configurations to the Javalin
 * server.
 *
 * <p>This class is responsible for setting up essential server features like JSON serialization
 * (with Jackson), enabling CORS, and registering default content types. This configuration is
 * applied once when the server starts.
 *
 * @author Generated by AI
 */
public class ServerConfig extends StartupConfig {

  private static final Logger log = LoggerFactory.getLogger(ServerConfig.class);
  private final ServerEnvironment env;

  public ServerConfig(JavalinConfig javalinConfig, ServerEnvironment env) {
    super(javalinConfig);
    this.env = env;
  }

  /** {@inheritDoc} */
  @Override
  public void apply() {
    javalinConfig.useVirtualThreads = true;
    javalinConfig.router.ignoreTrailingSlashes = true;
    javalinConfig.jetty.modifyServer(server -> server.setStopTimeout(5_000)); // graceful shutdown
    javalinConfig.http.defaultContentType = "application/json; charset=utf-8";
    String[] hosts = env.CORS_ALLOWED_ORIGINS();
    if (hosts != null && hosts.length > 0) {
      javalinConfig.bundledPlugins.enableCors(
          cors ->
              cors.addRule(
                  rule -> {
                    for (String h : hosts) {
                      rule.allowHost(h);
                    }
                    rule.allowCredentials = true;
                  }));
    } else {
      log.warn("CORS_ALLOWED_ORIGINS not set. CORS will reject all origins");
    }
    javalinConfig.jsonMapper(
        new JavalinJackson()
            .updateMapper(
                mapper -> mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)));
  }
}
