package com.anibalxyz.server.config.modules.startup;

import com.anibalxyz.server.config.AppEnv;

/**
 * Defines the contract for providing general server-level environment configuration.
 *
 * <p>This interface is used for settings that affect the overall server behavior, such as the
 * current runtime environment (e.g., "development", "production").
 *
 * @author Generated by AI
 */
public interface ServerEnvironment {
  /**
   * @return The current application environment (e.g., "development", "test").
   */
  AppEnv APP_ENV();

  /**
   * @return The base URL of the API.
   */
  String API_URL();

  String SERVER_URL();

  String API_PREFIX();

  String[] CORS_ALLOWED_ORIGINS();

  /**
   * @return The contact email for the API.
   */
  String CONTACT_EMAIL();
}
