package com.anibalxyz.server.config.modules.startup;

import com.anibalxyz.server.config.AppEnv;

/**
 * Defines the contract for providing general server-level environment configuration.
 *
 * <p>This interface is used for settings that affect the overall server behavior, such as the
 * current runtime environment (e.g., "development", "production").
 *
 * @author Generated by AI
 */
public interface ServerEnvironment {
  /**
   * Returns the current application environment (e.g., "development", "test").
   *
   * @return The current application environment.
   */
  AppEnv APP_ENV();

  /**
   * Returns the base URL of the API.
   *
   * @return The base URL of the API.
   */
  String API_URL();

  /**
   * Returns the root URL of the server.
   *
   * @return The root URL of the server.
   */
  String SERVER_URL();

  /**
   * Returns the API prefix for all routes.
   *
   * @return The API prefix.
   */
  String API_PREFIX();

  /**
   * Returns an array of allowed origins for Cross-Origin Resource Sharing (CORS).
   *
   * @return An array of allowed CORS origins.
   */
  String[] CORS_ALLOWED_ORIGINS();

  /**
   * Returns the contact email for the API.
   *
   * @return The contact email.
   */
  String CONTACT_EMAIL();
}
