services:
  prometheus:
    pull_policy: missing
    ports:
      - 9090:9090

  grafana:
    ports:
      - 3000:3000
    environment:
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
      - GF_SERVER_ROOT_URL=http://localhost:3000
