services:
  api:
    pull_policy: missing # In real production, this should be set to 'always'
  db:
    ports: !reset []
  nginx:
    image: anibalxyz/reconciler-prod-nginx:latest
    container_name: reconciler-prod-nginx
    pull_policy: missing # In real production, this should be set to 'always'
    ports:
      - "80:80"
    networks:
      - main
