services:
  db:
    ports:
      - "${DB_PORT}:5432"
    volumes:
      # Persistent storage for the DB. Data isn't lost on container shutdown
      - database:/var/lib/postgresql/data

  api:
    pull_policy: never
    volumes:
      # Mount source code and config for manual reload by restarting the container
      - ./backend/api/pom.xml:/app/pom.xml:cached
      - ./backend/api/src:/app/src:cached
      # Persist Maven dependencies cache to speed up builds
      - maven:/root/.m2

  dashboard:
    image: anibalxyz/reconciler-dev-dashboard:latest
    pull_policy: never
    container_name: reconciler-dev-dashboard
    env_file:
      - ./frontend/.env.dev
    ports:
      - "${DASHBOARD_PORT}:5174"
    volumes:
      # Enables hot reload by mounting source code and config files
      - ./frontend/dashboard/src:/app/dashboard/src:cached
      - ./frontend/dashboard/index.html:/app/dashboard/index.html:cached
      - ./frontend/dashboard/package.json:/app/dashboard/package.json:cached
      - ./frontend/dashboard/tsconfig.json:/app/dashboard/tsconfig.json:cached
      - ./frontend/dashboard/vite.config.ts:/app/dashboard/vite.config.ts:cached
      # Base frontend/ files
      - ./frontend/.env.dev:/app/.env.dev:cached
      - ./frontend/package.json:/app/package.json:cached
      - ./frontend/tsconfig.base.json:/app/tsconfig.base.json:cached
      - ./frontend/vite.config.ts:/app/vite.config.ts:cached
      # Cache subfrontend-specific node_modules
      - dashboard-node_modules:/app/node_modules:cached

    networks:
      - main

  public-site:
    image: anibalxyz/reconciler-dev-public-site:latest
    pull_policy: never
    container_name: reconciler-dev-public-site
    env_file:
      - ./frontend/.env.dev
    ports:
      - "${PUBLIC_SITE_PORT}:5173"
    volumes:
      # Enables hot reload by mounting source code and config files
      - ./frontend/public-site/src:/app/public-site/src:cached
      - ./frontend/public-site/pages:/app/public-site/pages:cached
      - ./frontend/public-site/package.json:/app/public-site/package.json:cached
      - ./frontend/public-site/tsconfig.json:/app/public-site/tsconfig.json:cached
      - ./frontend/public-site/vite.config.ts:/app/public-site/vite.config.ts:cached
      # Base frontend/ files
      - ./frontend/.env.dev:/app/.env.dev:cached
      - ./frontend/package.json:/app/package.json:cached
      - ./frontend/tsconfig.base.json:/app/tsconfig.base.json:cached
      - ./frontend/vite.config.ts:/app/vite.config.ts:cached
      # Cache subfrontend-specific node_modules
      - public-site-node_modules:/app/node_modules:cached
    networks:
      - main

volumes:
  maven:
    name: "reconciler-dev-mvn"
  dashboard-node_modules:
    name: "reconciler-dev-dahsboard-node"
  public-site-node_modules:
    name: "reconciler-dev-public-site-node"
