services:
  api:
    image: anibalxyz/reconciler-${APP_ENV}-api:latest
    container_name: reconciler-${APP_ENV}-api
    env_file:
      - ./backend/.env.${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
      - FRONTEND_PROTOCOL=${FRONTEND_PROTOCOL}
      # Override DB connection when running in the same Docker network
      # If using an external DB host, change to ${DB_HOST} or comment out
      # Since 'db' service lives in another yaml, if wanted to use ${} in test then it would warning
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - main

networks:
  main:
    name: reconciler-${APP_ENV}

volumes:
  database:
    name: reconciler-${APP_ENV}-db
