services:
  api:
    pull_policy: missing # In real production, this should be set to 'always'
    environment:
      - CORS_ALLOWED_ORIGINS=${NGINX_SERVER_NAME}
  db:
    ports: !reset []
  nginx:
    image: anibalxyz/reconciler-prod-nginx:latest
    container_name: reconciler-prod-nginx
    pull_policy: missing # In real production, this should be set to 'always'
    environment:
      # Use a short TTL in dev to allow quick DNS updates when containers restart.
      # In production, prefer a longer one to reduce DNS lookup overhead.
      - NGINX_TTL=${NGINX_TTL}
      - NGINX_PORT=${NGINX_PORT}
      - NGINX_SERVER_NAME=${NGINX_SERVER_NAME}
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - API_PORT=${API_PORT}
      - API_PREFIX=${API_PREFIX}
      # Used when running in the same Docker network. Change it in real production
      - API_HOST=api
    ports:
      - "80:80"
    networks:
      - main
