package com.anibalxyz.features.users.domain.exception;

/**
 * Thrown to indicate that a raw password does not meet the required format or complexity rules.
 *
 * <p>This exception is a subclass of {@link IllegalArgumentException} and is used to enforce
 * business rules about password constraints (e.g., minimum length, maximum length) before hashing.
 *
 * @author Generated by AI
 */
public class InvalidPasswordFormatException extends IllegalArgumentException {
  /**
   * Constructs an {@code InvalidPasswordFormatException} with the specified detail message.
   *
   * @param message The detail message.
   */
  public InvalidPasswordFormatException(String message) {
    super(message);
  }
}
