package com.anibalxyz.server.config;

import com.anibalxyz.users.application.EnvironmentSource;

/**
 * A concrete implementation of {@link EnvironmentSource} that holds application-level environment
 * variables.
 *
 * <p>This record provides a type-safe representation of settings loaded from the environment (e.g.,
 * .env files or system variables), preventing the use of "magic strings" throughout the codebase.
 *
 * @param APP_ENV The current application environment (e.g., "development", "test", "production").
 * @param BCRYPT_LOG_ROUNDS The computational cost for the BCrypt password hashing algorithm.
 * @author Generated by AI
 */
public record AppEnvironmentSource(String APP_ENV, int BCRYPT_LOG_ROUNDS)
    implements EnvironmentSource {}
