package com.anibalxyz.server.config;

/**
 * A record that provides a type-safe representation of application-level environment variables.
 *
 * <p>This class centralizes access to settings that are loaded from the environment, preventing the
 * use of "magic strings" throughout the codebase and making the configuration explicit.
 *
 * @param APP_ENV The current application environment (e.g., "development", "test", "production").
 * @param BCRYPT_LOG_ROUNDS The computational cost for the BCrypt password hashing algorithm.
 * @author Generated by AI
 */
public record EnvVarSet(String APP_ENV, int BCRYPT_LOG_ROUNDS) {}
