package com.anibalxyz.server.config;

/**
 * Represents a modular piece of server configuration logic.
 *
 * <p>This interface serves as a common contract for applying configuration modules. Implementations
 * encapsulate specific setup logic, such as registering exception handlers ({@link
 * ExceptionsConfig}), request lifecycle events ({@link LifeCycleConfig}), or initial server
 * settings ({@link InitConfig}). These modules are applied at different stages of the {@link
 * com.anibalxyz.server.Application} setup.
 *
 * @author Generated by AI
 */
public interface ServerConfig {
  void apply();
}
