package com.anibalxyz.persistence;

import jakarta.persistence.EntityManager;

/**
 * Defines a contract for providing a request-scoped {@link EntityManager}.
 *
 * <p>This interface decouples persistence-layer components (like repositories) from the specific
 * mechanism used to manage the EntityManager's lifecycle (e.g., Javalin's request context).
 *
 * @author Generated by AI
 */
public interface EntityManagerProvider {
  /**
   * @return The {@link EntityManager} for the current scope (e.g., the current HTTP request).
   */
  EntityManager get();
}
