package com.anibalxyz.server.config.environment;

import com.anibalxyz.features.auth.api.AuthApiEnvironment;
import com.anibalxyz.features.auth.application.env.AuthEnvironment;
import com.anibalxyz.features.auth.application.env.JwtEnvironment;
import com.anibalxyz.features.auth.application.env.RefreshTokenEnvironment;
import com.anibalxyz.features.users.application.UsersEnvironment;
import com.anibalxyz.server.config.modules.startup.ServerEnvironment;
import io.javalin.http.SameSite;
import java.time.Duration;

/**
 * A concrete implementation that holds application-level environment variables.
 *
 * <p>This record provides a type-safe representation of settings loaded from the environment (e.g.,
 * .env files or system variables), preventing the use of "magic strings" throughout the codebase.
 *
 * @param APP_ENV The current application environment (e.g., "dev", "test", "prod").
 * @param BCRYPT_LOG_ROUNDS The computational cost for the BCrypt password hashing algorithm.
 * @param API_URL The base URL of the API.
 * @param CONTACT_EMAIL The contact email for the API.
 * @author Generated by AI
 */
public record AppEnvironmentSource(
    String APP_ENV,
    int BCRYPT_LOG_ROUNDS,
    String API_URL,
    String CONTACT_EMAIL,
    String JWT_SECRET,
    String JWT_ISSUER,
    Duration JWT_ACCESS_EXPIRATION_TIME_MINUTES,
    Duration JWT_REFRESH_EXPIRATION_TIME_DAYS,
    Boolean AUTH_COOKIE_SECURE,
    String AUTH_COOKIE_DOMAIN,
    SameSite AUTH_COOKIE_SAMESITE,
    String AUTH_COOKIE_PATH)
    implements UsersEnvironment,
        ServerEnvironment,
        JwtEnvironment,
        RefreshTokenEnvironment,
        AuthApiEnvironment,
        AuthEnvironment {}
