package com.anibalxyz.server.config.environment;

import com.anibalxyz.features.auth.api.env.AuthApiEnvironment;
import com.anibalxyz.features.auth.application.env.AuthEnvironment;
import com.anibalxyz.features.auth.application.env.JwtEnvironment;
import com.anibalxyz.features.auth.application.env.RefreshTokenEnvironment;
import com.anibalxyz.features.users.application.env.UsersEnvironment;
import com.anibalxyz.server.config.AppEnv;
import com.anibalxyz.server.config.modules.startup.ServerEnvironment;
import io.javalin.http.SameSite;
import java.time.Duration;
import javax.crypto.SecretKey;

// TODO: check if can add used properties in javadocs of each interface
/**
 * A concrete implementation that holds application-level environment variables.
 *
 * <p>This record provides a type-safe representation of settings loaded from the environment (e.g.,
 * .env files or system variables), preventing the use of "magic strings" throughout the codebase.
 *
 * @param APP_ENV The current application environment (e.g., "dev", "test", "prod").
 * @param BCRYPT_LOG_ROUNDS The computational cost for the BCrypt password hashing algorithm.
 * @param API_URL The base URL of the API.
 * @param CONTACT_EMAIL The contact email for the API.
 * @author Generated by AI
 */
public record AppEnvironmentSource(
    AppEnv APP_ENV,
    String SERVER_URL,
    String API_URL,
    int API_PORT,
    String API_PREFIX,
    String[] CORS_ALLOWED_ORIGINS,
    String CONTACT_EMAIL,
    int BCRYPT_LOG_ROUNDS,
    String JWT_SECRET,
    SecretKey JWT_KEY,
    String JWT_ISSUER,
    long JWT_ACCESS_EXPIRATION_TIME_MINUTES,
    Duration JWT_REFRESH_EXPIRATION_TIME_DAYS,
    Boolean AUTH_COOKIE_SECURE,
    String AUTH_COOKIE_DOMAIN,
    SameSite AUTH_COOKIE_SAMESITE,
    String AUTH_COOKIE_PATH,
    boolean AUTH_ENABLE_TIME_WINDOW)
    implements UsersEnvironment,
        ServerEnvironment,
        JwtEnvironment,
        RefreshTokenEnvironment,
        AuthApiEnvironment,
        AuthEnvironment {}
