package com.anibalxyz.server.config.environment;

import com.anibalxyz.persistence.DatabaseVariables;

/**
 * An immutable container for all application configuration objects.
 *
 * <p>This record acts as a simple data holder for configuration properties that are loaded at
 * startup. It is created by the {@link ConfigurationFactory} and its contents are injected into the
 * various components of the application.
 *
 * @param env The application environment settings.
 * @param database The database connection settings.
 * @author Generated by AI
 */
public record ApplicationConfiguration(AppEnvironmentSource env, DatabaseVariables database) {}
