package com.anibalxyz.users.infra;

import com.anibalxyz.persistence.EntityManagerProvider;
import com.anibalxyz.users.domain.Email;
import com.anibalxyz.users.domain.User;
import com.anibalxyz.users.domain.UserRepository;
import jakarta.persistence.EntityManager;
import jakarta.persistence.NoResultException;
import java.util.List;
import java.util.Optional;

/**
 * JPA implementation of the {@link UserRepository} interface.
 *
 * <p>This class is an adapter that bridges the domain layer's persistence port (the repository
 * interface) with the actual data persistence technology (JPA/Hibernate). It handles all the
 * database operations for the {@link User} aggregate.
 *
 * @author Generated by AI
 */
public class JpaUserRepository implements UserRepository {

  private final EntityManagerProvider provider;

  /**
   * Constructs a JpaUserRepository.
   *
   * @param provider The provider used to get the current request's {@link EntityManager}.
   * @author Generated by AI
   */
  public JpaUserRepository(EntityManagerProvider provider) {
    this.provider = provider;
  }

  /**
   * @return The {@link EntityManager} for the current transaction.
   */
  private EntityManager em() {
    return provider.get();
  }

  @Override
  @SuppressWarnings("resource")
  public List<User> findAll() {
    List<UserEntity> userEntityList =
        em().createQuery("SELECT u FROM UserEntity u", UserEntity.class).getResultList();
    return userEntityList.stream().map(UserEntity::toDomain).toList();
  }

  @Override
  @SuppressWarnings("resource")
  public Optional<User> findById(Integer id) {
    UserEntity userEntity = em().find(UserEntity.class, id);
    return userEntity == null ? Optional.empty() : Optional.of(userEntity.toDomain());
  }

  @Override
  @SuppressWarnings("resource")
  public Optional<User> findByEmail(Email email) {
    try {
      UserEntity userEntity =
          em().createQuery("SELECT u FROM UserEntity u WHERE u.email = :email", UserEntity.class)
              .setParameter("email", email.value())
              .getSingleResult();
      return Optional.of(userEntity.toDomain());
    } catch (NoResultException e) {
      return Optional.empty();
    }
  }

  @Override
  @SuppressWarnings("resource")
  public User save(User user) throws IllegalArgumentException {
    UserEntity userEntity = em().merge(UserEntity.fromDomain(user));
    em().flush();
    return userEntity.toDomain();
  }

  @Override
  @SuppressWarnings("resource")
  public boolean deleteById(Integer id) {
    UserEntity userEntity = em().find(UserEntity.class, id);
    if (userEntity != null) {
      em().remove(userEntity);
      return true;
    }
    return false;
  }
}
