package com.anibalxyz.features.common.application.exception;

/**
 * Base class for all application-specific exceptions.
 *
 * <p>This abstract class serves as a marker interface and a common supertype for exceptions
 * that represent business rule violations or application-level errors. Exceptions extending
 * this class are typically caught by the web layer's exception handling mechanism
 * (e.g., {@code ExceptionsConfig}) and translated into appropriate HTTP responses.
 *
 * @author Generated by AI
 */
public abstract class ApplicationException extends RuntimeException {
  /**
   * Constructs a new ApplicationException with the specified detail message.
   *
   * @param message the detail message.
   */
  public ApplicationException(String message) {
    super(message);
  }
}
