package com.anibalxyz.features.common.application.exception;

/**
 * Exception thrown when a request cannot be completed due to a conflict with the current state of
 * the target resource.
 *
 * <p>This exception typically indicates a business rule violation where an operation would result
 * in an inconsistent or duplicate state (e.g., creating a user with an email that already exists).
 * It typically maps to an HTTP 409 Conflict status.
 *
 * @author Generated by AI
 */
public class ConflictException extends ApplicationException {
  /**
   * Constructs a new ConflictException with the specified detail message.
   *
   * @param message the detail message.
   */
  public ConflictException(String message) {
    super(message);
  }
}
