package com.anibalxyz.features.common.application.exception;

/**
 * Exception thrown when the application receives invalid input data.
 *
 * <p>This exception indicates that the provided data does not conform to expected formats,
 * constraints, or business rules. It typically maps to an HTTP 400 Bad Request status.
 *
 * @author Generated by AI
 */
public class InvalidInputException extends ApplicationException {
  /**
   * Constructs a new InvalidInputException with the specified detail message.
   *
   * @param message the detail message.
   */
  public InvalidInputException(String message) {
    super(message);
  }
}
