package com.anibalxyz.features.common.application.exception;

/**
 * Exception thrown when a requested resource (e.g., a User, a Transaction) cannot be found.
 *
 * <p>This exception indicates that the application could not find the specific resource identified
 * by the request. It typically maps to an HTTP 404 Not Found status.
 *
 * @author Generated by AI
 */
public class ResourceNotFoundException extends ApplicationException {
  /**
   * Constructs a new ResourceNotFoundException with the specified detail message.
   *
   * @param message the detail message.
   */
  public ResourceNotFoundException(String message) {
    super(message);
  }
}
