package com.anibalxyz.features;

import static com.anibalxyz.features.Constants.Environment.BCRYPT_LOG_ROUNDS;
import static com.anibalxyz.features.Constants.Users.VALID_PASSWORD;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.*;

import com.anibalxyz.features.users.domain.Email;
import com.anibalxyz.features.users.domain.PasswordHash;
import com.anibalxyz.features.users.domain.User;
import com.anibalxyz.features.users.infra.JpaUserRepository;
import com.anibalxyz.features.users.infra.UserEntity;
import com.anibalxyz.persistence.EntityManagerProvider;
import io.javalin.http.Context;
import io.javalin.http.Cookie;
import io.javalin.validation.BodyValidator;
import jakarta.persistence.EntityManager;
import org.mockito.ArgumentCaptor;
import org.mockito.stubbing.OngoingStubbing;

/**
 * A utility class providing helper methods for tests.
 *
 * <p>This class includes methods for mocking, capturing arguments, and managing the database state
 * during tests.
 *
 * @author Generated by AI
 */
public class Helpers {

  /**
   * Stubs the behavior of a Javalin {@link BodyValidator} for testing purposes.
   *
   * @param ctx The Javalin {@link Context} to mock.
   * @param clazz The class of the body validator.
   * @param <T> The type of the body.
   * @return An {@link OngoingStubbing} allowing further customization of the mocked validator.
   */
  @SuppressWarnings("unchecked")
  public static <T> OngoingStubbing<T> stubBodyValidatorFor(Context ctx, Class<T> clazz) {
    BodyValidator<T> mockValidator = (BodyValidator<T>) mock(BodyValidator.class);
    when(ctx.bodyValidator(clazz)).thenReturn(mockValidator);
    when(mockValidator.check(any(), anyString())).thenReturn(mockValidator);
    return when(mockValidator.get());
  }

  /**
   * Captures the JSON argument passed to {@link Context#json(Object)} for verification.
   *
   * @param ctx The Javalin {@link Context} mock.
   * @param clazz The class type to cast the captured JSON to.
   * @param <T> The type of the JSON object.
   * @return The captured JSON object.
   */
  public static <T> T capturedJsonAs(Context ctx, Class<T> clazz) {
    ArgumentCaptor<T> captor = ArgumentCaptor.forClass(clazz);
    verify(ctx).json(captor.capture());
    return captor.getValue();
  }

  /**
   * Captures the {@link Cookie} argument passed to {@link Context#cookie(Cookie)} for verification.
   *
   * @param ctx The Javalin {@link Context} mock.
   * @return The captured {@link Cookie} object.
   */
  public static Cookie capturedCookie(Context ctx) {
    ArgumentCaptor<Cookie> captor = ArgumentCaptor.forClass(Cookie.class);
    verify(ctx).cookie(captor.capture());
    return captor.getValue();
  }

  /**
   * Cleans all data from the public schema of the database by truncating all tables.
   *
   * @param em The {@link EntityManager} to use for database operations.
   */
  public static void cleanDatabase(EntityManager em) {
    em.getTransaction().begin();
    em.createNativeQuery(
            "DO $$ "
                + "DECLARE stmt text; "
                + "BEGIN "
                + "  SELECT 'TRUNCATE TABLE ' || string_agg(quote_ident(tablename), ', ') || ' RESTART IDENTITY CASCADE' "
                + "  INTO stmt "
                + "  FROM pg_tables "
                + "  WHERE schemaname = 'public'; "
                + "  EXECUTE stmt; "
                + "END $$;")
        .executeUpdate();
    em.getTransaction().commit();
  }

  /**
   * Capitalizes the first letter of a given string.
   *
   * @param s The input string.
   * @return The capitalized string, or the original string if null or empty.
   */
  public static String capitalize(String s) {
    if (s == null || s.isEmpty()) return s;
    return s.substring(0, 1).toUpperCase() + s.substring(1);
  }

  /**
   * Persists a new user to the database for testing purposes.
   *
   * @param em The {@link EntityManager} to use for persistence.
   * @param name The name of the user.
   * @param email The email of the user.
   * @return The persisted {@link UserEntity}.
   */
  public static UserEntity persistUser(EntityManager em, String name, String email) {
    em.getTransaction().begin();

    EntityManagerProvider emp = () -> em;
    User saved =
        new JpaUserRepository(emp)
            .save(
                new User(
                    name,
                    new Email(email),
                    PasswordHash.generate(VALID_PASSWORD, BCRYPT_LOG_ROUNDS)));

    em.getTransaction().commit();

    UserEntity entity = em.find(UserEntity.class, saved.getId());
    em.refresh(entity);
    return entity;
  }
}
