package com.anibalxyz.features;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.util.Map;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

/**
 * A utility class for making HTTP requests in integration tests.
 *
 * <p>This class simplifies the process of sending HTTP requests and parsing responses, providing a
 * convenient wrapper around OkHttp.
 *
 * @author Generated by AI
 */
public class HttpRequest {
  private final ObjectMapper mapper;
  private final OkHttpClient client;
  private final String baseUrl;

  /**
   * Constructs an {@code HttpRequest} instance.
   *
   * @param mapper The {@link ObjectMapper} for JSON serialization/deserialization.
   * @param client The {@link OkHttpClient} for making HTTP calls.
   * @param baseUrl The base URL for the API.
   */
  public HttpRequest(ObjectMapper mapper, OkHttpClient client, String baseUrl) {
    this.mapper = mapper;
    this.client = client;
    this.baseUrl = baseUrl;
  }

  private Response executeRequest(Request request) {
    try {
      return client.newCall(request).execute();
    } catch (IOException e) {
      throw new RuntimeException(e);
    }
  }

  /**
   * Sends an HTTP GET request to the specified path.
   *
   * @param path The API endpoint path.
   * @return The HTTP {@link Response}.
   */
  public Response get(String path) {
    return get(path, Map.of());
  }

  /**
   * @param path The API endpoint path.
   * @param headers The request headers.
   * @return The HTTP {@link Response}.
   */
  public Response get(String path, Map<String, String> headers) {
    Request.Builder requestBuilder = new Request.Builder().url(baseUrl + path).get();
    headers.forEach(requestBuilder::addHeader);
    return executeRequest(requestBuilder.build());
  }

  /**
   * Creates a JSON request body from the given object.
   *
   * @param body The object to be serialized to JSON.
   * @return The JSON request body.
   */
  @NotNull
  private okhttp3.RequestBody createJsonRequestBody(Object body) {
    try {
      String jsonBody =
          body.getClass().equals(String.class) ? (String) body : mapper.writeValueAsString(body);
      return okhttp3.RequestBody.create(jsonBody, okhttp3.MediaType.get("application/json"));
    } catch (IOException e) {
      throw new RuntimeException(e);
    }
  }

  /**
   * Sends an HTTP POST request to the specified path with the given body.
   *
   * @param path The API endpoint path.
   * @param body The request body object, which will be serialized to JSON.
   * @return The HTTP {@link Response}.
   */
  public Response post(String path, @NotNull Object body) {
    return post(path, body, Map.of());
  }

  /**
   * Sends an HTTP POST request to the specified path with the given body and headers.
   *
   * @param path The API endpoint path.
   * @param body The request body object, which will be serialized to JSON.
   * @param headers The request headers.
   * @return The HTTP {@link Response}.
   */
  public Response post(String path, @NotNull Object body, @NotNull Map<String, String> headers) {
    Request.Builder requestBuilder =
        new Request.Builder().url(baseUrl + path).post(createJsonRequestBody(body));
    headers.forEach(requestBuilder::addHeader);
    return executeRequest(requestBuilder.build());
  }

  /**
   * Sends an HTTP PUT request to the specified path with the given body.
   *
   * @param path The API endpoint path.
   * @param body The request body object, which will be serialized to JSON.
   * @return The HTTP {@link Response}.
   */
  public Response put(String path, Object body) {
    Request request =
        new Request.Builder().url(baseUrl + path).put(createJsonRequestBody(body)).build();
    return executeRequest(request);
  }

  /**
   * Sends an HTTP DELETE request to the specified path.
   *
   * @param path The API endpoint path.
   * @return The HTTP {@link Response}.
   */
  public Response delete(String path) {
    Request request = new Request.Builder().url(baseUrl + path).delete().build();
    return executeRequest(request);
  }

  /**
   * Parses the response body into an object of the specified type.
   *
   * @param response The HTTP {@link Response} containing the JSON body.
   * @param typeRef The {@link TypeReference} for the target type.
   * @param <T> The type to deserialize the response body into.
   * @return The deserialized object.
   */
  public <T> T parseBody(Response response, TypeReference<T> typeRef) {
    try (ResponseBody body = response.body()) {
      assertNotNull(body);
      return mapper.readValue(body.string(), typeRef);
    } catch (IOException e) {
      throw new RuntimeException(e);
    }
  }

  /**
   * Parses the response body into an object of the specified class.
   *
   * @param response The HTTP {@link Response} containing the JSON body.
   * @param clazz The {@link Class} for the target type.
   * @param <T> The type to deserialize the response body into.
   * @return The deserialized object.
   */
  public <T> T parseBody(Response response, Class<T> clazz) {
    try (ResponseBody body = response.body()) {
      assertNotNull(body);
      return mapper.readValue(body.string(), clazz);
    } catch (IOException e) {
      throw new RuntimeException(e);
    }
  }
}
