package com.anibalxyz.system.api;

import com.anibalxyz.system.api.out.HealthResponse;
import io.javalin.http.Context;
import io.javalin.openapi.HttpMethod;
import io.javalin.openapi.OpenApi;
import io.javalin.openapi.OpenApiContent;
import io.javalin.openapi.OpenApiResponse;

/**
 * Defines the API contract for system-level operations, such as health checks.
 *
 * <p>This interface uses {@link OpenApi} annotations to document the REST endpoints, providing a
 * clear specification for system-related functionalities. The {@link SystemController} implements
 * these operations.
 *
 * @author Generated by AI
 */
public interface SystemApi {

  /**
   * Handles GET requests to the /health endpoint.
   *
   * <p>This method provides a health check of the system, typically verifying connectivity to critical
   * services like the database.
   *
   * @param ctx The Javalin context object for the request.
   */
  @OpenApi(
      summary = "Health check",
      operationId = "healthCheck",
      path = "/health",
      methods = HttpMethod.GET,
      tags = {"System"},
      responses = {
        @OpenApiResponse(
            status = "200",
            description = "System status.",
            content = @OpenApiContent(from = HealthResponse.class))
      })
  void healthCheck(Context ctx);
}
