package com.anibalxyz.system.api;

import com.anibalxyz.server.routes.RouteGroup;
import com.anibalxyz.server.routes.RouteRegistry;
import io.javalin.Javalin;

/**
 * Registers system-related routes with the Javalin server.
 *
 * <p>This class extends {@link RouteRegistry} and defines the HTTP endpoints for system
 * functionalities, such as health checks. It maps the routes to the corresponding methods in the
 * {@link SystemApi} interface.
 *
 * @author Generated by AI
 */
public class SystemRoutes extends RouteRegistry {

  private final SystemApi systemApi;

  /**
   * Constructs a new SystemRoutes instance.
   *
   * @param server The Javalin server instance to which routes will be attached.
   * @param systemApi The API implementation that will handle the requests.
   */
  public SystemRoutes(Javalin server, SystemApi systemApi) {
    super(server);
    this.systemApi = systemApi;
  }

  /** {@inheritDoc} */
  @Override
  public void register() {
    new RouteGroup("/health", server).get("", systemApi::healthCheck);
  }
}
