package com.anibalxyz.server.config.modules.runtime;

import io.javalin.Javalin;

/**
 * Abstract base class for runtime configuration modules.
 *
 * <p>Runtime configuration modules are applied to a running {@link Javalin} server instance and
 * typically involve setting up handlers, filters, or other components that interact with the
 * request lifecycle.
 *
 * @author Generated by AI
 */
public abstract class RuntimeConfig {
  protected Javalin server;

  /**
   * Constructs a RuntimeConfig module.
   *
   * @param server The Javalin server instance to which the configuration will be applied.
   */
  public RuntimeConfig(Javalin server) {
    this.server = server;
  }

  /** Applies the runtime configuration logic to the Javalin server. */
  public abstract void apply();
}
