package com.anibalxyz.features.auth.application.exception;

import com.anibalxyz.features.common.application.exception.ApplicationException;

/**
 * Exception thrown when authentication credentials (e.g., username/password) are invalid.
 *
 * <p>This exception indicates that the provided credentials do not match any known user or are
 * otherwise incorrect, preventing successful authentication. It typically maps to an HTTP 401 Unauthorized status.
 *
 * @author Generated by AI
 */
public class InvalidCredentialsException extends ApplicationException {
  /**
   * Constructs a new InvalidCredentialsException with the specified detail message.
   *
   * @param message the detail message.
   */
  public InvalidCredentialsException(String message) {
    super(message);
  }
}
