package com.anibalxyz.server.routes;

import io.javalin.Javalin;
import io.javalin.http.Handler;

/**
 * A utility for defining a group of routes under a common path prefix.
 *
 * <p>This class provides a fluent API to chain route definitions (e.g., get, post), making the
 * registration of related endpoints more concise and readable. For example, all routes starting
 * with "/users" can be defined together.
 *
 * @author Generated by AI
 */
public class RouteGroup {
  private final String basePath;
  private final Javalin server;

  /**
   * Constructs a new RouteGroup.
   *
   * @param basePath The common path prefix for all routes in this group (e.g., "/users").
   * @param server The Javalin instance to which routes will be added.
   * @author Generated by AI
   */
  public RouteGroup(String basePath, Javalin server) {
    this.basePath = basePath;
    this.server = server;
  }

  /**
   * Registers a GET handler for a subpath within the group.
   *
   * @param path The subpath (e.g., "/{id}").
   * @param handler The request handler.
   * @return This {@link RouteGroup} instance for method chaining.
   * @author Generated by AI
   */
  public RouteGroup get(String path, Handler handler) {
    server.get(basePath + path, handler);
    return this;
  }

  /**
   * Registers a POST handler for a subpath within the group.
   *
   * @param path The subpath.
   * @param handler The request handler.
   * @return This {@link RouteGroup} instance for method chaining.
   * @author Generated by AI
   */
  public RouteGroup post(String path, Handler handler) {
    server.post(basePath + path, handler);
    return this;
  }

  /**
   * Registers a PUT handler for a subpath within the group.
   *
   * @param path The subpath.
   * @param handler The request handler.
   * @return This {@link RouteGroup} instance for method chaining.
   * @author Generated by AI
   */
  public RouteGroup put(String path, Handler handler) {
    server.put(basePath + path, handler);
    return this;
  }

  /**
   * Registers a DELETE handler for a subpath within the group.
   *
   * @param path The subpath.
   * @param handler The request handler.
   * @return This {@link RouteGroup} instance for method chaining.
   * @author Generated by AI
   */
  public RouteGroup delete(String path, Handler handler) {
    server.delete(basePath + path, handler);
    return this;
  }
}
