package com.anibalxyz.features.users.infra;

import com.anibalxyz.annotation.ExcludeFromJacocoGenerated;
import com.anibalxyz.features.common.Result;
import com.anibalxyz.features.users.domain.Email;
import com.anibalxyz.features.users.domain.Name;
import com.anibalxyz.features.users.domain.PasswordHash;
import com.anibalxyz.features.users.domain.User;
import com.anibalxyz.features.users.domain.error.InvalidPasswordHashError;
import com.anibalxyz.features.users.infra.exception.CorruptedEmail;
import com.anibalxyz.features.users.infra.exception.CorruptedName;
import com.anibalxyz.features.users.infra.exception.CorruptedPasswordHash;
import jakarta.persistence.*;
import java.time.Instant;
import org.hibernate.annotations.CurrentTimestamp;
import org.hibernate.generator.EventType;

/**
 * Represents the persistence model for a User, mapped to the "users" table.
 *
 * <p>This class is a JPA entity used by the infrastructure layer to interact with the database. It
 * contains mappers ({@link #fromDomain(User)} and {@link #toDomain()}) to convert between the rich
 * {@link User} domain model and this flat, persistence-oriented entity.
 *
 * @author Generated by AI
 */
@Entity
@Table(name = "users")
public class UserEntity {

  /** The unique identifier of the user. */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "id")
  private Integer id;

  /** The name of the user. */
  @Column(name = "name", nullable = false, length = 100)
  private String name;

  /** The email address of the user. Must be unique. */
  @Column(name = "email", nullable = false, unique = true, length = 255)
  private String email;

  /** The hashed password of the user. */
  @Column(name = "password_hash", nullable = false, length = 255)
  private String passwordHash;

  /** The timestamp when the user was created. */
  @CurrentTimestamp(event = EventType.INSERT)
  @Column(name = "created_at")
  private Instant createdAt;

  /** The timestamp when the user was last updated. */
  @CurrentTimestamp
  @Column(name = "updated_at")
  private Instant updatedAt;

  /** Default constructor required by JPA. */
  public UserEntity() {}

  /** Fully-parameterized constructor. */
  public UserEntity(
      Integer id,
      String name,
      String email,
      String passwordHash,
      Instant createdAt,
      Instant updatedAt) {
    this.id = id;
    this.name = name;
    this.email = email;
    this.passwordHash = passwordHash;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
  }

  /**
   * Creates a {@link UserEntity} from a {@link User} domain object. This static factory method is
   * used before persisting data.
   *
   * @param user The domain object to convert.
   * @return A new {@link UserEntity} instance.
   */
  public static UserEntity fromDomain(User user) {
    return new UserEntity(
        user.id(),
        user.name().value(),
        user.email().value(),
        user.passwordHash().value(),
        user.createdAt(),
        user.updatedAt());
  }

  /**
   * Converts this entity into a {@link User} domain object. This method is used after retrieving
   * data from the database.
   *
   * @return A new {@link User} domain object instance.
   */
  public User toDomain() {
    // Some branches will probably not be covered by the current acceptance tests.
    // Once unit tests are implemented, then full coverage will be possible
    Result<Email, ?> emailResult = Email.of(email);
    if (emailResult.isFailure()) throw new CorruptedEmail(email, id);
    Result<Name, ?> nameResult = Name.of(name);
    if (nameResult.isFailure()) throw new CorruptedName(name, id);
    Result<PasswordHash, InvalidPasswordHashError> passwordHashResult =
        PasswordHash.of(passwordHash);
    if (passwordHashResult.isFailure()) throw new CorruptedPasswordHash(passwordHash, id);

    return new User(
        id,
        nameResult.getValue(),
        emailResult.getValue(),
        passwordHashResult.getValue(),
        createdAt,
        updatedAt);
  }

  /**
   * Returns the unique identifier of the user.
   *
   * @return The user's ID.
   */
  @ExcludeFromJacocoGenerated
  public Integer getId() {
    return id;
  }

  /**
   * Sets the unique identifier of the user.
   *
   * @param id The new user ID.
   */
  @ExcludeFromJacocoGenerated
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * Returns the name of the user.
   *
   * @return The user's name.
   */
  @ExcludeFromJacocoGenerated
  public String getName() {
    return name;
  }

  /**
   * Sets the name of the user.
   *
   * @param name The new user name.
   */
  @ExcludeFromJacocoGenerated
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Returns the email address of the user.
   *
   * @return The user's email.
   */
  @ExcludeFromJacocoGenerated
  public String getEmail() {
    return email;
  }

  /**
   * Sets the email address of the user.
   *
   * @param email The new user email.
   */
  @ExcludeFromJacocoGenerated
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   * Returns the hashed password of the user.
   *
   * @return The user's password hash.
   */
  @ExcludeFromJacocoGenerated
  public String getPasswordHash() {
    return passwordHash;
  }

  /**
   * Sets the hashed password of the user.
   *
   * @param passwordHash The new password hash.
   */
  @ExcludeFromJacocoGenerated
  public void setPasswordHash(String passwordHash) {
    this.passwordHash = passwordHash;
  }

  /**
   * Returns the creation timestamp of the user.
   *
   * @return The creation timestamp.
   */
  @ExcludeFromJacocoGenerated
  public Instant getCreatedAt() {
    return createdAt;
  }

  /**
   * Sets the creation timestamp of the user.
   *
   * @param createdAt The new creation timestamp.
   */
  @ExcludeFromJacocoGenerated
  public void setCreatedAt(Instant createdAt) {
    this.createdAt = createdAt;
  }

  /**
   * Returns the last update timestamp of the user.
   *
   * @return The last update timestamp.
   */
  @ExcludeFromJacocoGenerated
  public Instant getUpdatedAt() {
    return updatedAt;
  }

  /**
   * Sets the last update timestamp of the user.
   *
   * @param updatedAt The new update timestamp.
   */
  @ExcludeFromJacocoGenerated
  public void setUpdatedAt(Instant updatedAt) {
    this.updatedAt = updatedAt;
  }
}
