package com.anibalxyz.features.auth.api;

import com.anibalxyz.server.routes.RouteGroup;
import com.anibalxyz.server.routes.RouteRegistry;
import io.javalin.Javalin;

/**
 * Registers authentication-related routes with the Javalin server.
 *
 * <p>This class extends {@link RouteRegistry} and defines the HTTP endpoints for authentication
 * functionalities, such as user login. It maps the routes to the corresponding methods in the
 * {@link AuthApi} interface.
 *
 * @author Generated by AI
 */
public class AuthRoutes extends RouteRegistry {
  private final AuthApi authApi;

  /**
   * Constructs a new AuthRoutes instance.
   *
   * @param server The Javalin server instance to which routes will be attached.
   * @param authApi The API implementation that will handle the requests.
   */
  public AuthRoutes(Javalin server, AuthApi authApi) {
    super(server);
    this.authApi = authApi;
  }

  /** {@inheritDoc} */
  @Override
  public void register() {
    new RouteGroup("/auth", server).post("/login", authApi::login);
  }
}
