package com.anibalxyz.features.auth.api;

import com.anibalxyz.features.auth.api.env.AuthApiEnvironment;
import com.anibalxyz.features.auth.api.in.LoginRequest;
import com.anibalxyz.features.auth.api.out.AuthResponse;
import com.anibalxyz.features.auth.application.AuthResult;
import com.anibalxyz.features.auth.application.AuthService;
import com.anibalxyz.features.auth.application.RefreshTokenService;
import io.javalin.http.*;
import java.time.Instant;

/**
 * Implements the {@link AuthApi} interface for handling authentication-related HTTP requests.
 *
 * <p>This controller provides endpoints for user login and token refreshing. It delegates
 * authentication logic to the {@link AuthService} and handles request validation and response
 * formatting, including setting secure cookies for refresh tokens.
 *
 * @author Generated by AI
 */
public class AuthController implements AuthApi {
  private final AuthApiEnvironment env;
  private final AuthService authService;
  private final RefreshTokenService refreshTokenService;

  /**
   * Constructs an AuthController with the given authentication service.
   *
   * @param authService The application service for authentication operations.
   */
  public AuthController(
      AuthApiEnvironment authApiEnvironment,
      AuthService authService,
      RefreshTokenService refreshTokenService) {
    this.env = authApiEnvironment;
    this.authService = authService;
    this.refreshTokenService = refreshTokenService;
  }

  /** {@inheritDoc} */
  @Override
  public void login(Context ctx) {
    LoginRequest request =
        ctx.bodyValidator(LoginRequest.class)
            .check(r -> r.email() != null && !r.email().isBlank(), "Email is required")
            .check(r -> r.password() != null && !r.password().isBlank(), "Password is required")
            .get();
    AuthResult authResult = authService.authenticateUser(request);
    long maxAgeInSeconds =
        Math.max(
            0,
            authResult.refreshToken().expiryDate().getEpochSecond()
                - Instant.now().getEpochSecond());

    setRefreshTokenCookie(ctx, authResult.refreshToken().token(), maxAgeInSeconds);
    ctx.status(200).json(new AuthResponse(authResult.accessToken()));
  }

  @Override
  public void logout(Context ctx) {
    String refreshTokenFromCookie = ctx.cookie("refreshToken");

    if (refreshTokenFromCookie != null) {
      refreshTokenService.revokeToken(refreshTokenFromCookie);
    }

    setRefreshTokenCookie(ctx, "", 0L);

    ctx.status(204);
  }

  @Override
  public void refresh(Context ctx) {
    String refreshTokenFromCookie = ctx.cookie("refreshToken");
    if (refreshTokenFromCookie == null) {
      throw new UnauthorizedResponse("Missing refresh token in cookie");
    }

    AuthResult authResult = authService.refreshTokens(refreshTokenFromCookie);

    long maxAgeInSeconds =
        Math.max(
            0,
            authResult.refreshToken().expiryDate().getEpochSecond()
                - Instant.now().getEpochSecond());

    setRefreshTokenCookie(ctx, authResult.refreshToken().token(), maxAgeInSeconds);
    ctx.status(200).json(new AuthResponse(authResult.accessToken()));
  }

  /**
   * Sets the refresh token as a secure, HttpOnly cookie in the response.
   *
   * @param ctx The Javalin context.
   * @param refreshToken The refresh token to be set in the cookie.
   */
  private void setRefreshTokenCookie(Context ctx, String refreshToken, long maxAgeInSeconds) {
    Cookie cookie =
        new Cookie(
            "refreshToken",
            refreshToken,
            env.AUTH_COOKIE_PATH(), //
            (int) maxAgeInSeconds,
            env.AUTH_COOKIE_SECURE(),
            0,
            true, // HttpOnly
            null, // Comment
            env.AUTH_COOKIE_DOMAIN(), // Domain
            SameSite.STRICT); // hardcoded to test
    ctx.cookie(cookie);
  }
}
