package com.anibalxyz.features.auth.api;

import com.anibalxyz.features.auth.api.in.LoginRequest;
import com.anibalxyz.features.auth.api.out.AuthResponse;
import com.anibalxyz.server.dto.ErrorResponse;
import com.anibalxyz.server.openapi.ErrorResponseExamples;
import io.javalin.http.Context;
import io.javalin.openapi.HttpMethod;
import io.javalin.openapi.OpenApi;
import io.javalin.openapi.OpenApiContent;
import io.javalin.openapi.OpenApiRequestBody;
import io.javalin.openapi.OpenApiResponse;

/**
 * Defines the API contract for authentication-related operations.
 *
 * <p>This interface uses {@link OpenApi} annotations to document the REST endpoints, providing a
 * clear specification for authentication functionalities. The {@link AuthController} implements
 * these operations.
 *
 * @author Generated by AI
 */
public interface AuthApi {

  @OpenApi(
      summary = "Authenticate user and get access token",
      operationId = "login",
      path = "/auth/login",
      methods = HttpMethod.POST,
      tags = {"Authentication"},
      requestBody =
          @OpenApiRequestBody(
              description = "User credentials for login",
              required = true,
              content = @OpenApiContent(from = LoginRequest.class)),
      responses = {
        @OpenApiResponse(
            status = "200",
            description =
                "Authentication successful. Returns access token in body, refresh token in HttpOnly cookie.",
            content = @OpenApiContent(from = AuthResponse.class)),
        @OpenApiResponse(
            status = "400",
            description = "Invalid input (e.g., missing email/password)",
            content =
                @OpenApiContent(
                    from = ErrorResponse.class,
                    example = ErrorResponseExamples.CREATE_USER_BAD_REQUEST)),
        @OpenApiResponse(
            status = "401",
            description = "Invalid credentials",
            content =
                @OpenApiContent(
                    from = ErrorResponse.class,
                    example = ErrorResponseExamples.INVALID_CREDENTIALS))
      })
  void login(Context ctx);

  @OpenApi(
      summary = "Refresh access token",
      operationId = "refreshToken",
      path = "/auth/refresh",
      methods = HttpMethod.POST,
      tags = {"Authentication"},
      responses = {
        @OpenApiResponse(
            status = "200",
            description =
                "Token refreshed successfully. Returns new access token in body, new refresh token in HttpOnly cookie.",
            content = @OpenApiContent(from = AuthResponse.class)),
        @OpenApiResponse(
            status = "401",
            description = "Invalid or expired refresh token.",
            content =
                @OpenApiContent(
                    from = ErrorResponse.class,
                    example = ErrorResponseExamples.INVALID_CREDENTIALS)),
        @OpenApiResponse(
            status = "400",
            description = "Bad request (e.g., missing refresh token).",
            content = @OpenApiContent(from = ErrorResponse.class))
      })
  void refresh(Context ctx);
}
