package com.anibalxyz.features.auth.api;

import com.anibalxyz.features.auth.api.in.LoginRequest;
import com.anibalxyz.features.auth.api.out.AuthResponse;
import com.anibalxyz.features.auth.application.AuthService;
import io.javalin.http.Context;

/**
 * Handles HTTP requests for authentication-related operations.
 *
 * <p>This controller provides endpoints for user login and token generation. It delegates
 * authentication logic to the {@link AuthService} and handles request parsing and response
 * formatting.
 *
 * @author Generated by AI
 */
public class AuthController implements AuthApi {
  private final AuthService authService;

  /**
   * Constructs an AuthController with the given authentication service.
   *
   * @param authService The application service for authentication operations.
   */
  public AuthController(AuthService authService) {
    this.authService = authService;
  }

  /**
   * {@inheritDoc}
   *
   * <p>Handles user login requests. Validates the provided email and password, authenticates the
   * user, and returns a JWT token upon successful authentication.
   *
   * @param ctx The Javalin context for the request.
   */
  @Override
  public void login(Context ctx) {
    LoginRequest request =
        ctx.bodyValidator(LoginRequest.class)
            .check(r -> r.email() != null && !r.email().isBlank(), "Email is required")
            .check(r -> r.password() != null && !r.password().isBlank(), "Password is required")
            .get();
    String token = authService.authenticateUser(request);
    ctx.status(200).json(new AuthResponse(token));
  }
}
