package com.anibalxyz.features.auth.api;

import com.anibalxyz.features.auth.api.env.AuthApiEnvironment;
import com.anibalxyz.features.auth.api.in.LoginRequest;
import com.anibalxyz.features.auth.api.out.AuthResponse;
import com.anibalxyz.features.auth.application.AuthService;
import com.anibalxyz.features.auth.application.RefreshTokenService;
import com.anibalxyz.features.auth.application.in.LoginCommand;
import com.anibalxyz.features.auth.application.out.AuthResult;
import com.anibalxyz.features.common.Result;
import com.anibalxyz.features.common.application.exception.FailureSignal;
import io.javalin.http.*;
import java.time.Clock;

/**
 * Implements the {@link AuthApi} interface for handling authentication-related HTTP requests.
 *
 * <p>This controller provides endpoints for user login and token refreshing. It delegates
 * authentication logic to the {@link AuthService} and handles request validation and response
 * formatting, including setting secure cookies for refresh tokens.
 *
 * @author Generated by AI
 */
public class AuthController implements AuthApi {
  public static final String REFRESH_TOKEN_COOKIE = "refreshToken";
  private final AuthApiEnvironment env;
  private final AuthService authService;
  private final RefreshTokenService refreshTokenService;
  private final Clock clock;

  /**
   * Constructs an AuthController with the given authentication service.
   *
   * @param authService The application service for authentication operations.
   */
  public AuthController(
      AuthApiEnvironment authApiEnvironment,
      AuthService authService,
      RefreshTokenService refreshTokenService,
      Clock clock) {
    this.env = authApiEnvironment;
    this.authService = authService;
    this.refreshTokenService = refreshTokenService;
    this.clock = clock;
  }

  /** {@inheritDoc} */
  @Override
  public void login(Context ctx) {
    LoginCommand command = ctx.bodyAsClass(LoginRequest.class).toCommand();
    Result<AuthResult, AuthService.AuthenticateUserError> authResult =
        authService.authenticateUser(command);
    if (authResult.isFailure()) {
      throw new FailureSignal(authResult.getError());
    }
    AuthResult authResultValue = authResult.getValue();

    setRefreshTokenCookie(
        ctx,
        authResultValue.refreshToken().token(),
        authResultValue.refreshToken().secondsUntilExpiry(clock.instant()));
    ctx.status(200).json(new AuthResponse(authResultValue.accessToken()));
  }

  /** {@inheritDoc} */
  @Override
  public void logout(Context ctx) {
    String refreshTokenFromCookie = ctx.cookie("refreshToken");

    refreshTokenService.revokeToken(refreshTokenFromCookie);

    emptyRefreshTokenCookie(ctx);

    ctx.status(204);
  }

  @Override
  public void refresh(Context ctx) {
    String refreshTokenFromCookie = ctx.cookie("refreshToken");
    if (refreshTokenFromCookie == null || refreshTokenFromCookie.isBlank()) {
      throw new UnauthorizedResponse("Missing refresh token in cookie");
    }

    Result<AuthResult, AuthService.RefreshTokensError> authResult =
        authService.refreshTokens(refreshTokenFromCookie);

    if (authResult.isFailure()) {
      throw new FailureSignal(authResult.getError());
    }

    AuthResult authResultValue = authResult.getValue();

    setRefreshTokenCookie(
        ctx,
        authResultValue.refreshToken().token(),
        authResultValue.refreshToken().secondsUntilExpiry(clock.instant()));
    ctx.status(200).json(new AuthResponse(authResultValue.accessToken()));
  }

  private void emptyRefreshTokenCookie(Context ctx) {
    setRefreshTokenCookie(ctx, "", 0L);
  }

  /**
   * Sets the refresh token as a secure, HttpOnly cookie in the response.
   *
   * @param ctx The Javalin context.
   * @param refreshToken The refresh token to be set in the cookie.
   */
  private void setRefreshTokenCookie(Context ctx, String refreshToken, long maxAgeInSeconds) {
    Cookie cookie =
        new Cookie(
            REFRESH_TOKEN_COOKIE,
            refreshToken,
            env.AUTH_COOKIE_PATH(), //
            (int) maxAgeInSeconds,
            env.AUTH_COOKIE_SECURE(),
            0,
            true, // HttpOnly
            null, // Comment
            env.AUTH_COOKIE_DOMAIN(), // Domain
            env.AUTH_COOKIE_SAMESITE());
    ctx.cookie(cookie);
  }
}
