package com.anibalxyz;

import com.anibalxyz.server.Application;
import com.anibalxyz.server.config.environment.ApplicationConfiguration;
import com.anibalxyz.server.config.environment.ConfigurationFactory;

/**
 * The main entry point for the application.
 *
 * @author Generated by AI
 */
public class Main {

  /**
   * Starts the web server.
   *
   * @param args Command line arguments (not used).
   */
  public static void main(String[] args) {
    ApplicationConfiguration config = ConfigurationFactory.loadFromEnv();
    Application server = Application.create(config);

    Runtime.getRuntime().addShutdownHook(new Thread(server::stop));

    server.start(config.env().API_PORT());
  }
}
