FROM anibalxyz/reconciler-production-dashboard AS dashboard
FROM anibalxyz/reconciler-production-public-site AS public-site

FROM nginx:stable-alpine AS final

COPY nginx.conf /etc/nginx/nginx.conf

COPY 404.html /usr/share/nginx/html/404.html

COPY --from=dashboard /app/dashboard/dist /usr/share/nginx/html/dashboard

COPY --from=public-site /app/public-site/dist /usr/share/nginx/html
