CREATE TABLE REFRESH_TOKENS (
  ID BIGSERIAL PRIMARY KEY,
  TOKEN VARCHAR(255) NOT NULL UNIQUE,
  USER_ID INTEGER NOT NULL,
  EXPIRY_DATE TIMESTAMPTZ NOT NULL,
  REVOKED BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT FK_REFRESH_TOKENS_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE
);