package com.anibalxyz.server.context;

import com.anibalxyz.persistence.EntityManagerProvider;
import jakarta.persistence.EntityManager;

/**
 * An implementation of {@link EntityManagerProvider} that retrieves the {@link EntityManager} from
 * the Javalin request context.
 *
 * <p>This class acts as an adapter, allowing persistence-layer components (like {@link
 * com.anibalxyz.users.infra.JpaUserRepository}) to obtain the current, request-scoped {@code
 * EntityManager} without having a direct dependency on Javalin's {@code Context}. It relies on the
 * {@link ContextProvider} to access the context.
 *
 * @author Generated by AI
 */
public class JavalinContextEntityManagerProvider implements EntityManagerProvider {

  /**
   * {@inheritDoc}
   */
  @Override
  public EntityManager get() {
    return ContextProvider.get().attribute("em");
  }
}
