package com.anibalxyz.users.application.in;

/**
 * Defines the contract for incoming data payloads for creating or updating a user.
 *
 * <p>This interface is used by the {@link com.anibalxyz.users.application.UserService} to decouple
 * it from the specific DTOs of the API layer. Any request object (like UserCreateRequest or
 * UserUpdateRequest) that provides user data must implement this interface.
 *
 * @author Generated by AI
 */
public interface UserUpdatePayload {
  /**
   * @return The user's name.
   */
  String name();

  /**
   * @return The user's email.
   */
  String email();

  /**
   * @return The user's raw (plain-text) password.
   */
  String password();
}
