package com.anibalxyz.features.users.api;

import com.anibalxyz.features.common.application.exception.ConflictException;
import com.anibalxyz.features.common.application.exception.ResourceNotFoundException;
import com.anibalxyz.features.users.api.in.UserCreateRequest;
import com.anibalxyz.features.users.api.in.UserUpdateRequest;
import com.anibalxyz.features.users.api.out.UserDetailResponse;
import com.anibalxyz.features.users.application.UserService;
import com.anibalxyz.features.users.domain.User;
import io.javalin.http.BadRequestResponse;
import io.javalin.http.Context;
import io.javalin.validation.ValidationException;
import java.util.List;

/**
 * Handles HTTP requests for the /users resource.
 *
 * <p>This class provides the concrete implementation for the {@link UserApi} interface. It is
 * responsible for parsing requests, calling the {@link UserService} to execute business logic, and
 * formatting the HTTP responses.
 *
 * @author Generated by AI
 */
public class UserController implements UserApi {
  private final UserService userService;

  /**
   * Constructs a UserController with the given user service.
   *
   * @param userService The application service for user operations.
   */
  public UserController(UserService userService) {
    this.userService = userService;
  }

  /** {@inheritDoc} */
  @Override
  public void getAllUsers(Context ctx) {
    List<User> users = userService.getAllUsers();
    List<UserDetailResponse> response = users.stream().map(UserMapper::toDetailResponse).toList();
    ctx.status(200).json(response);
  }

  /** {@inheritDoc} */
  @Override
  public void getUserById(Context ctx) throws BadRequestResponse, ResourceNotFoundException {
    int id = getParamId(ctx);
    ctx.status(200).json(UserMapper.toDetailResponse(userService.getUserById(id)));
  }

  /** {@inheritDoc} */
  @Override
  public void createUser(Context ctx) throws ConflictException, ValidationException {
    UserCreateRequest request =
        ctx.bodyValidator(UserCreateRequest.class)
            .check(r -> r.name() != null && !r.name().isBlank(), "Name is required")
            .check(r -> r.email() != null && !r.email().isBlank(), "Email is required")
            .check(r -> r.password() != null && !r.password().isBlank(), "Password is required")
            .get();

    ctx.status(201).json(UserMapper.toCreateResponse(userService.createUser(request)));
  }

  /** {@inheritDoc} */
  @Override
  public void updateUserById(Context ctx)
      throws ConflictException, ValidationException, ResourceNotFoundException, BadRequestResponse {
    int id = getParamId(ctx);

    String badRequestMessage = "At least one field (name, email, password) must be provided";

    UserUpdateRequest userUpdateRequest =
        ctx.bodyValidator(UserUpdateRequest.class)
            .check(UserUpdateRequest::hasAtLeastOneField, badRequestMessage)
            .get();

    ctx.status(200)
        .json(UserMapper.toDetailResponse(userService.updateUserById(id, userUpdateRequest)));
  }

  /** {@inheritDoc} */
  @Override
  public void deleteUserById(Context ctx) throws ResourceNotFoundException, BadRequestResponse {
    userService.deleteUserById(getParamId(ctx));
    ctx.status(204);
  }

  /**
   * Extracts and validates the 'id' path parameter from the context.
   *
   * @param ctx The Javalin context.
   * @return The validated integer ID.
   * @throws BadRequestResponse if the ID is missing or not a valid integer.
   */
  private int getParamId(Context ctx) throws BadRequestResponse {
    return ctx.pathParamAsClass("id", Integer.class)
        .getOrThrow(e -> new BadRequestResponse("Invalid ID format. Must be a number."));
  }
}
