package com.anibalxyz.features.users.api;

import com.anibalxyz.features.common.api.routing.RouteGroup;
import com.anibalxyz.features.common.api.routing.RouteRegistry;
import com.anibalxyz.server.security.Role;
import io.javalin.Javalin;

/**
 * Registers all API routes related to the User resource.
 *
 * <p>This class groups all user-related endpoints (like GET, POST, PUT, DELETE for /users) and maps
 * them to the corresponding methods in the {@link UserController}. It extends {@link RouteRegistry}
 * to be discoverable by the main application's routing setup.
 *
 * @author Generated by AI
 */
public class UserRoutes extends RouteRegistry {
  private final UserApi userApi;

  /**
   * Constructs a UserRoutes object.
   *
   * @param server The Javalin server instance.
   * @param userApi The controller that handles user-related requests.
   */
  public UserRoutes(Javalin server, UserApi userApi) {
    super(server);
    this.userApi = userApi;
  }

  /** {@inheritDoc} */
  public void register() {
    new RouteGroup("/users", server)
        .get(userApi::getAllUsers, Role.AUTHENTICATED)
        .post(userApi::createUser, Role.GUEST)
        .get("/{id}", userApi::getUserById, Role.AUTHENTICATED)
        .put("/{id}", userApi::updateUserById, Role.AUTHENTICATED)
        .delete("/{id}", userApi::deleteUserById, Role.AUTHENTICATED);
  }
}
