package com.anibalxyz.features.users.api;

import com.anibalxyz.features.common.Result;
import com.anibalxyz.features.common.application.ValidationNotification;
import com.anibalxyz.features.common.application.exception.AppException;
import com.anibalxyz.features.users.api.in.UserCreateRequest;
import com.anibalxyz.features.users.api.in.UserUpdateRequest;
import com.anibalxyz.features.users.api.out.UserDetailResponse;
import com.anibalxyz.features.users.application.UserService;
import com.anibalxyz.features.users.application.in.CreateUserCommand;
import com.anibalxyz.features.users.domain.User;
import com.anibalxyz.features.users.domain.error.UserNotFoundError;
import io.javalin.http.BadRequestResponse;
import io.javalin.http.Context;
import java.util.List;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Handles HTTP requests for the /users resource.
 *
 * <p>This class provides the concrete implementation for the {@link UserApi} interface. It is
 * responsible for parsing requests, calling the {@link UserService} to execute business logic, and
 * formatting the HTTP responses.
 *
 * @author Generated by AI
 */
public class UserController implements UserApi {
  private static final Logger log = LoggerFactory.getLogger(UserController.class);
  private final UserService userService;

  /**
   * Constructs a UserController with the given user service.
   *
   * @param userService The application service for user operations.
   */
  public UserController(UserService userService) {
    this.userService = userService;
  }

  /** {@inheritDoc} */
  @Override
  public void getAllUsers(Context ctx) {
    List<User> users = userService.getAllUsers();
    List<UserDetailResponse> response = users.stream().map(UserMapper::toDetailResponse).toList();
    ctx.status(200).json(response);
  }

  /** {@inheritDoc} */
  @Override
  public void getUserById(Context ctx) throws BadRequestResponse {
    int id = getParamId(ctx);
    Result<User, UserNotFoundError> result = userService.getUserById(id);
    if (result.isFailure()) {
      throw new AppException(result.getError());
    }

    ctx.status(200).json(UserMapper.toDetailResponse(result.getValue()));
  }

  /** {@inheritDoc} */
  @Override
  public void createUser(Context ctx) {
    CreateUserCommand command = ctx.bodyAsClass(UserCreateRequest.class).toCommand();

    Result<User, ValidationNotification> result = userService.createUser(command);

    if (result.isFailure()) {
      throw new AppException(result.getError());
    }

    ctx.status(201).json(UserMapper.toCreateResponse(result.getValue()));
  }

  /** {@inheritDoc} */
  @Override
  public void updateUserById(Context ctx) throws BadRequestResponse {
    int id = getParamId(ctx);

    UserUpdateRequest userUpdateRequest = ctx.bodyAsClass(UserUpdateRequest.class);
    Result<User, UserService.UpdateUserByIdError> result =
        userService.updateUserById(id, userUpdateRequest.toCommand());

    if (result.isFailure()) {
      throw new AppException(result.getError());
    }

    ctx.status(200).json(UserMapper.toDetailResponse(result.getValue()));
  }

  /** {@inheritDoc} */
  @Override
  public void deleteUserById(Context ctx) throws BadRequestResponse {
    int id = getParamId(ctx);
    Result<Void, UserNotFoundError> result = userService.deleteUserById(id);
    if (result.isFailure()) {
      throw new AppException(result.getError());
    }
    ctx.status(204);
  }

  /**
   * Extracts and validates the 'id' path parameter from the context.
   *
   * @param ctx The Javalin context.
   * @return The validated integer ID.
   * @throws BadRequestResponse if the ID is missing or not a valid integer.
   */
  private int getParamId(Context ctx) throws BadRequestResponse {
    return ctx.pathParamAsClass("id", Integer.class)
        .getOrThrow(e -> new BadRequestResponse("Invalid ID format. Must be a number."));
  }
}
