package com.anibalxyz.users.api;

import com.anibalxyz.server.routes.RouteGroup;
import com.anibalxyz.server.routes.RouteRegistry;
import io.javalin.Javalin;

/**
 * Registers all API routes related to the User resource.
 *
 * <p>This class groups all user-related endpoints (like GET, POST, PUT, DELETE for /users) and maps
 * them to the corresponding methods in the {@link UserController}. It extends {@link RouteRegistry}
 * to be discoverable by the main application's routing setup.
 *
 * @author Generated by AI
 */
public class UserRoutes extends RouteRegistry {
  private final UserApi userApi;

  /**
   * Constructs a UserRoutes object.
   *
   * @param server The Javalin server instance.
   * @param userApi The controller that handles user-related requests.
   * @author Generated by AI
   */
  public UserRoutes(Javalin server, UserApi userApi) {
    super(server);
    this.userApi = userApi;
  }

  public void register() {
    new RouteGroup("/users", server)
        .get("", userApi::getAllUsers)
        .post("", userApi::createUser)
        .get("/{id}", userApi::getUserById)
        .put("/{id}", userApi::updateUserById)
        .delete("/{id}", userApi::deleteUserById);
  }
}
