package com.anibalxyz.users.api;

import com.anibalxyz.server.routes.RouteGroup;
import com.anibalxyz.server.routes.RouteRegistry;
import io.javalin.Javalin;

/**
 * Registers all API routes related to the User resource.
 *
 * <p>This class groups all user-related endpoints (like GET, POST, PUT, DELETE for /users) and maps
 * them to the corresponding methods in the {@link UserController}. It extends {@link RouteRegistry}
 * to be discoverable by the main application's routing setup.
 *
 * @author Generated by AI
 */
public class UserRoutes extends RouteRegistry {
  private final UserController userController;

  /**
   * Constructs a UserRoutes object.
   *
   * @param server The Javalin server instance.
   * @param userController The controller that handles user-related requests.
   * @author Generated by AI
   */
  public UserRoutes(Javalin server, UserController userController) {
    super(server);
    this.userController = userController;
  }

  public void register() {
    new RouteGroup("/users", server)
        .get("", userController::getAllUsers)
        .post("", userController::createUser)
        .get("/{id}", userController::getUserById)
        .put("/{id}", userController::updateUserById)
        .delete("/{id}", userController::deleteUserById);
  }
}
