package com.anibalxyz.server.config.modules;

import com.anibalxyz.persistence.PersistenceManager;
import com.anibalxyz.server.context.ContextProvider;
import io.javalin.Javalin;
import jakarta.persistence.EntityManager;

/**
 * A {@link ServerConfig} module for managing per-request lifecycle events.
 *
 * <p>This class hooks into Javalin's request lifecycle to handle resources that need to be created
 * and torn down for each HTTP request. Its primary responsibility is to manage the JPA {@link
 * EntityManager}, ensuring that one is created at the beginning of a request and properly closed at
 * the end, whether the request succeeds or fails.
 *
 * @author Generated by AI
 */
public class LifeCycleConfig implements ServerConfig {

  private final Javalin server;
  private final PersistenceManager persistenceManager;

  /**
   * Constructs a LifeCycleConfig.
   *
   * @param server The Javalin instance to attach the lifecycle handlers to.
   * @param persistenceManager The manager for the persistence layer, used to create the
   *     EntityManager.
   */
  public LifeCycleConfig(Javalin server, PersistenceManager persistenceManager) {
    this.server = server;
    this.persistenceManager = persistenceManager;
  }

  /**
   * Configures the before/after handlers to manage the EntityManager and its transaction for each
   * request.
   */
  private void setEntityManagerLifecycle() {
    server.before(
        ctx -> {
          ContextProvider.set(ctx);
          EntityManager em = persistenceManager.emf().createEntityManager();
          em.getTransaction().begin();
          ctx.attribute("em", em);
        });
    server.after(
        ctx -> {
          EntityManager em = ctx.attribute("em");
          boolean existsEm = em != null && em.isOpen();
          try {
            if (!existsEm || !em.getTransaction().isActive()) {
              return;
            }

            if (ctx.status().getCode() >= 400) {
              em.getTransaction().rollback();
            } else {
              em.getTransaction().commit();
            }

          } finally {
            if (existsEm) em.close();
            ContextProvider.clear();
          }
        });
  }

  /** {@inheritDoc} */
  @Override
  public void apply() {
    setEntityManagerLifecycle();
  }
}
