package com.anibalxyz.server.config.modules;

/**
 * Defines the contract for providing general server-level environment configuration.
 *
 * <p>This interface is used for settings that affect the overall server behavior, such as the
 * current runtime environment (e.g., "development", "production").
 *
 * @author Generated by AI
 */
public interface ServerEnvironment {
  /**
   * @return The current application environment (e.g., "development", "test").
   */
  String APP_ENV();

  String API_URL();

  String CONTACT_EMAIL();
}
