package com.anibalxyz.server.config.modules;

import com.anibalxyz.server.config.modules.definitions.ServerEnvironment;
import com.anibalxyz.server.config.modules.definitions.StartupConfig;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.fasterxml.jackson.databind.node.TextNode;
import io.javalin.config.JavalinConfig;
import io.javalin.openapi.plugin.OpenApiPlugin;
import io.javalin.openapi.plugin.swagger.SwaggerPlugin;

/**
 * Configuration for OpenAPI documentation and Swagger UI integration.
 *
 * <p>This configuration sets up comprehensive API documentation including detailed project
 * information, contact details, license information, and server configurations. The OpenAPI
 * specification follows industry standards and provides complete API documentation for the
 * Reconciler financial transaction reconciliation application.
 *
 * <p>Key features:
 *
 * <ul>
 *   <li>Comprehensive project metadata and description
 *   <li>Contact information and repository links
 *   <li>MIT license specification
 *   <li>Server configuration for different environments
 *   <li>Swagger UI integration with custom paths
 * </ul>
 *
 * @author Generated by AI
 */
public class SwaggerConfig extends StartupConfig {

  private final ServerEnvironment env;

  public SwaggerConfig(JavalinConfig javalinConfig, ServerEnvironment env) {
    super(javalinConfig);
    this.env = env;
  }

  /** {@inheritDoc} */
  @Override
  public void apply() {
    String infoDescription =
"""
Financial transaction reconciliation API for teams to reconcile transactions between bank statements and internal
systems. Built with clean architecture principles, domain-driven design, and comprehensive testing strategies.
""";
    javalinConfig.registerPlugin(
        new OpenApiPlugin(
            openApiConfig ->
                openApiConfig
                    .withDocumentationPath("/openapi")
                    .withDefinitionConfiguration(
                        (version, definition) ->
                            definition
                                .withInfo(
                                    info ->
                                        info.title("Reconciler API")
                                            .version("1.0-SNAPSHOT")
                                            .description(infoDescription)
                                            // .termsOfService
                                            // ("https://github.com/anibalxyz/reconciler/blob/main/README.md")
                                            .contact(
                                                "Anibal Boggio",
                                                "https://github.com/anibalxyz",
                                                env.CONTACT_EMAIL())
                                            .license(
                                                "MIT License",
                                                "https://github.com/anibalxyz/reconciler/blob/main/LICENSE",
                                                "MIT"))
                                .withServer(
                                    server ->
                                        server
                                            .description(env.APP_ENV() + " server")
                                            .url(env.API_URL()))
                                .withSecurity(
                                    openApiSecurity -> openApiSecurity.withBearerAuth("bearerAuth"))
                                .withDefinitionProcessor(
                                    content -> {
                                      ObjectNode externalDocs = content.objectNode();
                                      externalDocs.set(
                                          "description",
                                          new TextNode("Project Repository and Documentation"));
                                      externalDocs.set(
                                          "url",
                                          new TextNode("https://github.com/anibalxyz/reconciler"));
                                      content.set("externalDocs", externalDocs);

                                      // Add global tags for the API organization
                                      var tagsArray = content.arrayNode();

                                      var usersTag = content.objectNode();
                                      usersTag.set("name", new TextNode("Users"));
                                      usersTag.set(
                                          "description",
                                          new TextNode(
                                              """
                                              User management operations including CRUD functionality,
                                              authentication, and authorization features.
                                              """
                                                  .trim()));
                                      tagsArray.add(usersTag);

                                      var authTag = content.objectNode();
                                      authTag.set("name", new TextNode("Authentication"));
                                      authTag.set(
                                          "description",
                                          new TextNode(
                                              """
                                              Endpoints for user authentication, including login and logout.
                                              """
                                                  .trim()));
                                      tagsArray.add(authTag);

                                      var systemTag = content.objectNode();
                                      systemTag.set("name", new TextNode("System"));
                                      systemTag.set(
                                          "description",
                                          new TextNode(
                                              """
                                              System-level operations, such as health checks and status monitoring.
                                              """
                                                  .trim()));
                                      tagsArray.add(systemTag);

                                      content.set("tags", tagsArray);

                                      return content.toPrettyString();
                                    }))));

    if (env.APP_ENV().equals("dev")) {
      javalinConfig.registerPlugin(
          new SwaggerPlugin(
              swaggerConfig -> {
                swaggerConfig.setUiPath("/swagger");
              }));
    }
  }
}
