package com.anibalxyz.features.users.domain;

import com.anibalxyz.annotation.ExcludeFromJacocoGenerated;
import java.time.Instant;
import org.jetbrains.annotations.NotNull;

/**
 * Represents a User in the domain.
 *
 * <p>This class is the root entity for the User aggregate. It is designed to be immutable; any
 * modification returns a new {@code User} instance with the updated value using the {@code with...}
 * methods. This ensures predictable state management and thread safety.
 *
 * @author Generated by AI
 */
public record User(
    Integer id,
    Name name,
    Email email,
    PasswordHash passwordHash,
    Instant createdAt,
    Instant updatedAt) {
  @ExcludeFromJacocoGenerated(reason = "SoC violated - will be deleted once removed from OpenAPI ")
  public static final int NAME_MAX_LENGTH = 100;

  /**
   * Constructor for creating a new user that has not yet been persisted. The ID, createdAt, and
   * updatedAt fields are initialized to null.
   *
   * @param name The user's name.
   * @param email The user's email address.
   * @param passwordHash The user's hashed password.
   */
  public User(Name name, Email email, PasswordHash passwordHash) {
    this(null, name, email, passwordHash, null, null);
  }

  /**
   * Creates a new User instance with an updated ID.
   *
   * @param id The new ID.
   * @return A new {@code User} instance.
   */
  public User withId(Integer id) {
    return new User(id, name, email, passwordHash, createdAt, updatedAt);
  }

  /**
   * Creates a new User instance with an updated name.
   *
   * @param name The new name.
   * @return A new {@code User} instance.
   */
  public User withName(Name name) {
    return new User(id, name, email, passwordHash, createdAt, updatedAt);
  }

  /**
   * Creates a new User instance with an updated email.
   *
   * @param email The new email.
   * @return A new {@code User} instance.
   */
  public User withEmail(Email email) {
    return new User(id, name, email, passwordHash, createdAt, updatedAt);
  }

  /**
   * Creates a new User instance with an updated password hash.
   *
   * @param passwordHash The new password hash.
   * @return A new {@code User} instance.
   */
  public User withPasswordHash(PasswordHash passwordHash) {
    return new User(id, name, email, passwordHash, createdAt, updatedAt);
  }

  /**
   * Creates a new User instance with an updated creation timestamp.
   *
   * @param createdAt The new creation timestamp.
   * @return A new {@code User} instance.
   */
  public User withCreatedAt(Instant createdAt) {
    return new User(id, name, email, passwordHash, createdAt, updatedAt);
  }

  /**
   * Creates a new User instance with an updated modification timestamp.
   *
   * @param updatedAt The new modification timestamp.
   * @return A new {@code User} instance.
   */
  public User withUpdatedAt(Instant updatedAt) {
    return new User(id, name, email, passwordHash, createdAt, updatedAt);
  }

  /** Returns a string representation of the user, masking the password hash. */
  @Override
  public @NotNull String toString() {
    return
"""
User(id=%s, name=%s, email=%s, passwordHash=%s, createdAt=%s, updatedAt=%s)"""
        .formatted(id, name.value(), email.value(), passwordHash.toString(), createdAt, updatedAt);
  }
}
