package com.anibalxyz.server.openapi;

// TODO: divide it into feature-specific examples
/**
 * Provides standardized, reusable JSON example strings for OpenAPI error responses.
 *
 * <p>This class centralizes common error message formats to ensure consistency across the API
 * documentation and to simplify maintenance. Each constant represents a complete JSON object string
 * that can be used directly in {@code @OpenApiContent(example = ...)}.
 *
 * <p>The class is final and has a private constructor to prevent instantiation.
 *
 * @author Generated by AI
 */
public final class ErrorResponseExamples {

  /** Example response for requests with an invalid ID format (e.g., non-numeric). */
  public static final String INVALID_ID =
      """
            {
              "error": "Bad Request",
              "details": [
                "Invalid ID format. Must be a number."
              ]
            }""";

  /** Example response for when a requested entity (like a user) is not found. */
  public static final String USER_NOT_FOUND =
      """
            {
              "error": "Entity not found",
              "details": [
                "User with id 1 not found"
              ]
            }""";

  /** Example response for a user creation request with missing or invalid data. */
  public static final String CREATE_USER_BAD_REQUEST =
      """
            {
              "error": "Invalid input provided",
              "details": [
                "Name is required"
              ]
            }""";

  /** Example response for a user update request that provides no updatable fields. */
  public static final String UPDATE_USER_BAD_REQUEST =
      """
            {
              "error": "Invalid input provided",
              "details": [
                "At least one field (name, email, password) must be provided"
              ]
            }""";

  /** Example response for requests missing or providing invalid authentication tokens. */
  public static final String UNAUTHORIZED =
      """
            {
              "error": "Unauthorized",
              "details": [
                "Authentication information is missing or invalid."
              ]
            }""";

  /** Example response for invalid authentication credentials. */
  public static final String INVALID_CREDENTIALS =
      """
            {
              "error": "Invalid credentials",
              "details": []
            }""";

  /** Example response for a generic, unexpected server error. */
  public static final String INTERNAL_SERVER_ERROR =
      """
            {
              "error": "Internal Server Error",
              "details": []
            }""";

  /** Private constructor to prevent instantiation. */
  private ErrorResponseExamples() {}
}
