package com.anibalxyz.features.auth.api.in;

import com.anibalxyz.features.auth.application.in.LoginPayload;
import io.javalin.openapi.OpenApiExample;
import io.javalin.openapi.OpenApiRequired;
import io.javalin.openapi.OpenApiStringValidation;

/**
 * Represents the request body for user login.
 *
 * <p>This record serves as a Data Transfer Object (DTO) for incoming POST requests to /auth/login.
 * It implements the {@link LoginPayload} interface, allowing it to be passed to the application
 * service layer. Both fields are mandatory for authentication.
 *
 * @param email The user's email address.
 * @param password The user's raw (plain-text) password.
 * @author Generated by AI
 */
public record LoginRequest(
    @OpenApiExample("john.doe@example.com")
        @OpenApiRequired
        @OpenApiStringValidation(format = "email")
        String email,
    @OpenApiExample("strong-password-123") @OpenApiRequired String password)
    implements LoginPayload {}
