package com.anibalxyz.features.auth.application;

import java.time.Duration;

/**
 * Defines the contract for providing authentication-related environment configuration.
 *
 * <p>This interface acts as a port for environment-dependent settings required by the authentication
 * feature, such as JWT secret, issuer, and expiration time. It decouples the {@link AuthService}
 * from the concrete source of configuration.
 *
 * @author Generated by AI
 */
public interface AuthEnvironment {
  /**
   * @return The secret key used for signing and verifying JWT tokens.
   */
  String JWT_SECRET();

  /**
   * @return The issuer of the JWT tokens.
   */
  String JWT_ISSUER();

  /**
   * @return The expiration time for JWT tokens.
   */
  Duration JWT_EXPIRATION_TIME();
}
