package com.anibalxyz.features.auth.application;

import com.anibalxyz.features.auth.domain.RefreshToken;

/**
 * A DTO to hold the result of a successful authentication, containing both access and refresh
 * tokens.
 *
 * @param accessToken The short-lived JWT access token.
 * @param refreshToken The long-lived refresh token.
 * @author Generated by AI
 */
public record AuthResult(String accessToken, RefreshToken refreshToken) {}
