package com.anibalxyz.features.auth.application;

import com.anibalxyz.features.auth.domain.RefreshToken;
import com.anibalxyz.features.auth.domain.RefreshTokenRepository;
import com.anibalxyz.features.auth.domain.error.InvalidRefreshTokenError;
import com.anibalxyz.features.common.Result;
import com.anibalxyz.features.users.domain.User;
import java.time.*;
import java.util.Optional;
import java.util.UUID;

/**
 * Service for handling Refresh Token operations, including generation, validation, and rotation.
 *
 * <p>This class encapsulates the logic for creating and managing refresh tokens, ensuring they are
 * securely stored and associated with a user. It acts as the primary entry point for refresh
 * token-related use cases.
 *
 * @author Generated by AI
 */
public class RefreshTokenService {
  private final RefreshTokenRepository refreshTokenRepository;

  /**
   * Constructs a RefreshTokenService with its required dependencies.
   *
   * @param refreshTokenRepository The repository for refresh token persistence.
   */
  public RefreshTokenService(RefreshTokenRepository refreshTokenRepository) {
    this.refreshTokenRepository = refreshTokenRepository;
  }

  /**
   * Creates and persists a new refresh token for a given user.
   *
   * <p>This method generates a unique token value and sets its expiration date based on the
   * environment configuration. If the time-window feature is enabled, the expiration date may be
   * capped to the end of the current window.
   *
   * @param user The user for whom the token is being created.
   * @return The newly created and persisted {@link RefreshToken}.
   */
  public RefreshToken createRefreshToken(User user, Instant expiryDate) {
    return refreshTokenRepository.save(
        new RefreshToken(null, UUID.randomUUID().toString(), user, expiryDate, false));
  }

  public Result<RefreshToken, InvalidRefreshTokenError> verifyAndRotate(
      String token, Instant now, Instant expiryDate) {
    Result<RefreshToken, InvalidRefreshTokenError> verifyResult = verifyRefreshToken(token, now);
    if (verifyResult.isFailure()) {
      return Result.failure(verifyResult.getError());
    }

    RefreshToken oldToken = verifyResult.getValue();
    refreshTokenRepository.save(oldToken.withRevoked(true));
    return Result.success(createRefreshToken(oldToken.user(), expiryDate));
  }

  public Result<RefreshToken, InvalidRefreshTokenError> verifyRefreshToken(
      String token, Instant now) {
    Optional<RefreshToken> found = refreshTokenRepository.findByToken(token);
    if (found.isEmpty()) {
      return Result.failure(InvalidRefreshTokenError.notFound());
    }

    RefreshToken refreshToken = found.get();

    if (refreshToken.isExpired(now)) {
      // NOTE: here could add logic to invalidate all tokens for the user
      // if an expired token is used, as it could signal a token theft attempt.
      return Result.failure(InvalidRefreshTokenError.expired());
    }

    if (refreshToken.revoked()) {
      // NOTE: here could add logic to invalidate all tokens for the user
      // if a revoked token is used, as it could signal a token theft attempt.
      return Result.failure(InvalidRefreshTokenError.revoked());
    }

    return Result.success(refreshToken);
  }

  /**
   * Revokes a refresh token if it exists.
   *
   * <p>This method finds a refresh token by its value and, if found, marks it as revoked in the
   * repository. If the token is null or not found, the method does nothing.
   *
   * @param token The refresh token string to revoke.
   */
  public void revokeToken(String token) {
    if (token == null || token.isBlank()) return;

    refreshTokenRepository
        .findByToken(token)
        .ifPresent((refreshToken) -> refreshTokenRepository.save(refreshToken.withRevoked(true)));
  }

  /**
   * Cleans up expired refresh tokens from the data store.
   *
   * @return The number of deleted tokens.
   */
  public int cleanupExpiredTokens() {
    return refreshTokenRepository.deleteExpiredTokens();
  }
}
